### ISSUE TITLE
add support for more than one spw

### ISSUE THREAD

**Issue by dannyjacobs** [RadioAstronomySoftwareGroup/pyuvdata#1]
currently support the reading in of multiple spws into the data column, but frequencies are not imported correctly from AIPS FQ table (see pg 9 of AIPS memo 117 ftp://ftp.aoc.nrao.edu/pub/software/aips/TEXT/PUBL/AIPSMEM117.PDF)

**Comment by kartographer** [comment]
Fresh off of (and perhaps a bit over confident from) our first successful PR, I'd like to actually begin pushing on this a bit and see where I can get, particularly as we'd like to have this ability for SMA (where we've got currently up to 24 spws, and that number may go up to 32 in the not-so-distant future). I've done a bit of scoping out the code, and I don't see any immediate roadblocks for implementing this for the UVData, Mir, or UVFITS classes (though probably a lot of potential for trial-and-error), although I need some assistance enabling this capability for the other formats (if it were so desired). I'll start up a branch shortly...
