### ISSUE TITLE
Error when reading scaled mwa_corr_fits data

### ISSUE THREAD

**Issue by PyxieLouStar** [RadioAstronomySoftwareGroup/pyuvdata#1003]
After some point in 2014, MWA data was stored as integers with the `'BSCALE'` keyword encoding time and frequency averaging. Using `memap=True` in `astropy.io.fits.read()` on this data throws the error `ValueError("Cannot load a memory-mapped image: BZERO/BSCALE/BLANK header keywords present. Set memmap=False.")`.

**Comment by PyxieLouStar** [comment]
This should have been caught during tests. When 2015 data files were truncated into test files, the `BSCALE` keyword was lost.

**Comment by mkolopanis** [comment]
Fascinating! probably a change I made during the first memory bloat issue. Do we not explicitly test against a post 2015 datafile?

**Comment by PyxieLouStar** [comment]
We do. The problem is that I had to modify the 2015 file to make it small enough for an upload, and in that process inadvertently destroyed the `BSCALE` keyword.
