### ISSUE TITLE
CircleCI fails to build when a PR is from a fork

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvdata#1029]
Something leads CircleCI to replace characters (specifically `+` and `/`) in the wheel's version string with characters that are not PEP 440 compliant (specifically `-`).  After a telecon's worth of investigation, we can't find out why or where this change is happening.  It seems like PRs from forks are rare enough that this can be solved by overriding the CircleCI checks if everything else passes -- but that requires us to remember this is an issue.

**Comment by mkolopanis** [comment]
@plaplant  pointed out that another option would be to set the `SETUPTOOLS_SCM_PRETEND_VERSION` env variable explicitly for circleci builds to get around this.
