### ISSUE TITLE
Add a CI check for warnings in tests

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyuvdata#1040]
Add a check that runs pytest with `-W error` to turn warnings into errors. Make this a non-blocking CI check so we get notified if there are warnings but it doesn't block merging PRs.

**Comment by mkolopanis** [comment]
The [pytest docs](https://docs.pytest.org/en/6.2.x/warnings.html) also have a little section about using the `-W` argument or even setting it automatically in a pytest.ini/pyproject.toml
