### ISSUE TITLE
FHD cal metadata read error

### ISSUE THREAD

**Issue by rlbyrne** [RadioAstronomySoftwareGroup/pyuvdata#1043]
I'm finding that the `read_fhd_cal` function errors when `read_data=False`.  Error is `TypeError: object of type 'NoneType' has no len()`

My call is `cal_obj.read_fhd_cal('1061316296_cal.sav', '1061316296_obs.sav', read_data=False)`. I can provide the files.

**Comment by bhazelton** [comment]
Interesting. Can you paste in the full stack trace so I can see what line it's erroring on?

**Comment by rlbyrne** [comment]
Here's the full trace:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ruby/opt/anaconda3/lib/python3.8/site-packages/pyuvdata/uvcal/uvcal.py", line 2309, in read_fhd_cal
    fhd_cal_obj.read_fhd_cal(
  File "/Users/ruby/opt/anaconda3/lib/python3.8/site-packages/pyuvdata/uvcal/fhd_cal.py", line 365, in read_fhd_cal
    "Tile" + "0" * (3 - len(self.ref_antenna_name)) + self.ref_antenna_name
TypeError: object of type 'NoneType' has no len()

**Comment by bhazelton** [comment]
I see the problem. If you want to do a metadata only read you need to provide a settings file because there is some metadata that can only come from the settings file or a full read of the data. Unfortunately the error you're getting doesn't tell you that. Can you confirm that it works if you provide a settings file? I will work on a PR to give a better error message.

**Comment by rlbyrne** [comment]
I just tried with a settings file and got this error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ruby/opt/anaconda3/lib/python3.8/site-packages/pyuvdata/uvcal/uvcal.py", line 2309, in read_fhd_cal
    fhd_cal_obj.read_fhd_cal(
  File "/Users/ruby/opt/anaconda3/lib/python3.8/site-packages/pyuvdata/uvcal/fhd_cal.py", line 275, in read_fhd_cal
    diffuse_model = settings_lines["diffuse_model"][0]
IndexError: list index out of range

**Comment by bhazelton** [comment]
Interesting. Can you check to see if diffuse_model appears in the settings file (or point me to the settings file so I can check)? If it doesn't always appear in the file I will need to wrap that call in an if statement.

**Comment by rlbyrne** [comment]
It looks like diffuse_model is empty in the settings file, which is odd. The settings file is on S3 here: s3://mwa-data/diffuse_survey/fhd_rlb_perfreq_cal_Feb2021/metadata/1061316296_settings.txt

**Comment by bhazelton** [comment]
Ok, I added some handling for no diffuse model in the settings file in PR #1044. I tested it by adding your settings file to our test data, so I think it should work for you, but let me know if there are any issues. If you're up for reviewing that PR it might get merged faster :wink:.

**Comment by rlbyrne** [comment]
Looks good! I just approved the PR.
