### ISSUE TITLE
Error reading MS file

### ISSUE THREAD

**Issue by akvydula** [RadioAstronomySoftwareGroup/pyuvdata#1070]
I have been trying to look at the pulsar observation from VLA+LWA1+LWASV using pyuvdata, and I have been running into this error, maybe someone here could know about this: when I read the ms files, I get 
`ValueError: UVParameter antenna_diameters is not expected shape. Parameter shape is (0,), expected shape is (30,)`. 
 does this have to do something with the file itself or is there anything in pyuvdata that can help read it?

Here's the link to download the data file: https://drive.google.com/drive/folders/1AhxjW2A6ZgeCzkSA3qXv8QsrFRQZNibF?usp=sharing

**Comment by bhazelton** [comment]
This was resolved with by installing a more recent version of pyuvdata.
