### ISSUE TITLE
Adding flexible polarization handling for spectral windows

### ISSUE THREAD

**Issue by kartographer** [RadioAstronomySoftwareGroup/pyuvdata#1076]
The Submillimeter Array has the capability to separately tune the two polarizations we are sensible to (i.e., V & H), which is typically used to provide additional spectral coverage of the interferometer. As such, we effectively have different spectral windows which do not have the same polarization.

Both the SMA MIR and CASA MS formats support the ability to support such an operating mode, but `UVData` objects do not yet as of the writing of this issue. One workaround would be to label everything effectively Stokes I, although that results in some loss of information about the data which is less-than-desirable. One alternative could be the addition of an optional attribute, `flex_spw_polarization` (which would only be used when `flex_spw=True`), an array on `ints` with length `Nspws`, which would allow for the assignment of polarization on a per-window basis.

**Comment by bhazelton** [comment]
Need a new array of length Nspws listing the polarization per spectral window. Could only be written out to measurement sets and miriad.
