### ISSUE TITLE
Errors in reading GMRT UVFITS data

### ISSUE THREAD

**Issue by shriharshtendulkar** [RadioAstronomySoftwareGroup/pyuvdata#1104]
I'm getting the following error in reading UVFITS data from GMRT (using python 3.8.5):
`UnboundLocalError: local variable 'xyz_telescope_frame' referenced before assignment` 

In `uvfits.py`, `xyz_telescope_frame` needs to be defined and initialized to a default value outside the if/else block before it is used (before line 624).

I corrected this for my local file. Then I get the following error:

```~/.local/lib/python3.8/site-packages/pyuvdata/uvdata/uvfits.py in _get_parameter_data(self, vis_hdu, run_check_acceptability, background_lsts)
    142                 np.stack(
    143                     (
--> 144                         vis_hdu.data.par("UU"),
    145                         vis_hdu.data.par("VV"),
    146                         vis_hdu.data.par("WW"),

~/.local/lib/python3.8/site-packages/astropy/io/fits/hdu/groups.py in par(self, parname)
    237             result = self.field(parname)
    238         else:
--> 239             indx = self._unique[parname.upper()]
    240             if len(indx) == 1:
    241                 result = self.field(indx[0])

KeyError: 'UU'
```

The file has keywords 'UU---SIN', 'VV---SIN', 'WW---SIN'
According to the AIPS convention (http://parac.eu/AIPSMEM117.pdf), the keywords are usually 'UU, VV, WW' but may be followed by modifiers '---SIN' (default) or '---NCP'.

Could you add these to the uvfits reader?

**Comment by bhazelton** [comment]
@shriharshtendulkar thank you for this report. I'm a little confused about the first error you describe because `xyz_telescope_frame` is set in both branches of the if/else block. Can you point me to a place I can download a file that has this error so I can understand what's going on? If not, then can you paste the full stack trace here?

For the baseline coordinate keywords we can add support for the `SIN` or `NCP` suffixes, I'll make a PR for that soon.

**Comment by bhazelton** [comment]
I now have a PR to add support for suffixes on the baseline coordinates (linked above).

**Comment by bhazelton** [comment]
I'm wondering if the error you're seeing with the `xyz_telescope_frame` is on an older version of pyuvdata, I can't quite reconcile the error as you describe it with the current code in the main branch. Can you report what version of pyuvdata you're using?

**Comment by shriharshtendulkar** [comment]
Hi @bhazelton , thanks for looking into this so quickly! I'm also surprised at the `xyz_telescope_frame` behaviour. I'm using pyuvdata version 2.2.4 with python 3.8.5.
This does get fixed when `xyz_telescope_frame` is first defined outside the if/else block.


I'll check out the UV suffixes bug.

**Comment by bhazelton** [comment]
Can you provide a link to download a file that is giving you the error about the `xyz_telescope_frame` so I can try to understand what is going on?

**Comment by shriharshtendulkar** [comment]
Hi @bhazelton : I've put a 1.2 GB GMRT visibilities file here: https://www.dropbox.com/t/FptXsUsdZzucnqbl Let me know if you are able to recreate the error.

**Comment by bhazelton** [comment]
Thank you @shriharshtendulkar, I got the file. When I'm on the `uvfits_uvw_suffix` branch (which fixes the uvw coordinate suffix issues) that file reads in without errors. So it seems like the `xyz_telescope_frame` is no longer an issue. Thank you so much for the file, it's nice to be able to confirm that my fix for the suffix issue works on your files.

**Comment by shriharshtendulkar** [comment]
@bhazelton Thanks a lot for fixing this so quickly. I'll checkout your branch.
