### ISSUE TITLE
Memory issue with write_ms

### ISSUE THREAD

**Issue by akvydula** [RadioAstronomySoftwareGroup/pyuvdata#1111]
One of my MS files has incorrect antenna positions. I am trying to use `pyuvdata` to compute ECEF from ENU (`pyuvdata.utils.ECEF_from_ENU`) and then using uvd.write_ms  to create an updated MS file. But everytime I do this, the jypyter notebook is crashing or the cluster I am using is reaching OOM. The file itself is about 14GB but `uvd.write_ms`  is taking more than 130GB. Any leads on how to solve this?

More about the file:

Nfreqs: 279
Nblts:  1012770
Nspws:  1
Npols:  4

**Comment by bhazelton** [comment]
Hi @akvydula, thank you for the report! @kartographer thinks he has identified the issue and is working on a PR that should fix it. We'll let you know when it's ready for you to try out if you like.

**Comment by bhazelton** [comment]
@akvydula The PR linked above dramatically decreases the memory required by `write_ms`. We will try to get it in soon, but in the meantime you can test it if you like by checking out the `ms_improved` branch. If you get a chance to test it, please let us know what you find!

**Comment by bhazelton** [comment]
@akvydula The improved memory handling has now been merged into the main branch.

**Comment by akvydula** [comment]
Hi @bhazelton and @kartographer. I tested the writer after a git pull, but it is still OOMing the cluster.

**Comment by kartographer** [comment]
@akvydula -- just to confirm, is this the same file as before (~14 GB in size)? And did you happen to get a traceback when the OOM error occured?

**Comment by akvydula** [comment]
Yes, it is the same file. We have a new task manager now that just kills the task if it gets close to OOMing the cluster. I saw the memory go up to ~130GB before it was automatically killed.

**Comment by kartographer** [comment]
Hmm... testing locally on my macbook, I'm not able to replicate the issue (the call to `write_ms` does increase the memory used of my local python session by about 50%, although that's nowhere near the order-of-mag you're seeing). Can you check the version of pyuvdata you are using by running `import pyuvdata; print(pyuvdata.__version__)`?

**Comment by akvydula** [comment]
I am on version: `2.2.3.dev8+ge64c57aa`

**Comment by kartographer** [comment]
That might explain it -- I believe the changes above went in at v2.2.5. Can you update and see if it works after that?

**Comment by akvydula** [comment]
That helped and the writer works fine now, thanks so much!
