### ISSUE TITLE
Wrapping bug in uvd.print_phase_center_info

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyuvdata#1130]
Where you can get RAs of 350 hours.

**Comment by akvydula** [comment]
Here's a sample output from `uvd.print_phase_center_info()`

   ID     Cat Entry       Type     Az/Lon/RA    El/Lat/Dec  Frame    Epoch
    #          Name                    hours           deg
---------------------------------------------------------------------------
    0      CYGNUS_A   sidereal   355:59:28.36  +40:44:02.10    fk5  J2000.0
    1         3C196   sidereal    8:13:36.06  +48:13:02.64    fk5  J2000.0
    2         3C295   sidereal   350:11:20.65  +52:12:09.14    fk5  J2000.0
    3         B1133   sidereal   11:36:03.12  +15:51:14.18    fk5  J2000.0
