### ISSUE TITLE
Importing `miriad.py` fails on M1 Mac platforms

### ISSUE THREAD

**Issue by plaplant** [RadioAstronomySoftwareGroup/pyuvdata#1131]
I've recently switched to using [miniforge3](https://github.com/conda-forge/miniforge) for the new Apple Silicon architecture to use natively-built extensions, and tried to run pyuvdata's tests. Evidently, the `np.float128` type is not available on this platform (at least in the pre-built packages available from conda), and leads to an `AttributeError` when used. It seems we only use it in one particular place in `miriad.py`, when defining a mapping between numpy types and miriad types for writing `extra_keywords`:

https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/fb2e721f0b0dfd0dab642e94c19dfac02fefd7c1/pyuvdata/uvdata/miriad.py#L1857-L1876

It seems like it's not used outside of this dictionary definition, and all tests pass if we remove that line. According to the [numpy docs on extended precision](https://numpy.org/doc/stable/user/basics.types.html#extended-precision), most platforms do not provide higher precision than `np.longdouble` anyway, which is typically 80 bits of precision for x86 machines but is 64 bits for Windows and osx-arm64. I'd vote for either removing that key from the dictionary (I doubt users are trying to write quad-precision numbers to extra keywords entries...), or replacing it with `np.longdouble` for better compatibility.

**Comment by mkolopanis** [comment]
I think i would vote for longdouble, which creates yet another question, should the other version be replaced by their named counterparts?
