### ISSUE TITLE
Parameter scan_number_array is not updated during select

### ISSUE THREAD

**Issue by rlbyrne** [RadioAstronomySoftwareGroup/pyuvdata#1159]
I am reading a ms file and then attempting to select the autocorrelations only with `uvd.select(ant_str="auto", run_check=False)`. Both before and after the select the parameter `scan_number_array` has length equal to the total number of baselines. The select therefore fails if I set `run_check=True`. I can avoid the issue by setting `uvd.scan_number_array=None` initially.

**Comment by kartographer** [comment]
This looks like it was an oversight when we added the `scan_number_array` parameter -- a quick fix to this is easy (a one-line edit in `_select_metadata`), although I'd like to take a whack at actually making this more robust by having `select` look at `UVParameter.form` to determine if a subset along a particular axis needs to be extracted. I'll take a crack at it...

**Comment by kartographer** [comment]
@rlbyrne -- #1171 should have fixed this, so you should no longer need the work-around of setting `UVData.scan_number_array=None`, but let me know if it gives you any further trouble!
