### ISSUE TITLE
UVBeam set-up fails to set up object without explicitly calling `_set_efield()`

### ISSUE THREAD

**Issue by slosar** [RadioAstronomySoftwareGroup/pyuvdata#1160]
When setting up UVBeam object from scratch, setting E-field mode by calling
```
uvb.beam_type = 'efield'
```
fails to create object correctly even if `check()` passes as evidence by trying to dump it to fits and then reading it back in.
Instead, this works:
```
uvb._set_efield()
uvb.pixel_coordinate_system = "az_za"
uvb._set_cs_params()
```
But this is i) not obvious and ii) calls internal functions which is not kosher. 
Full script: 
https://github.com/lusee-night/luseepy/blob/sky_models/simulations/beams/scripts/make_beam.py

**Comment by bhazelton** [comment]
It turns out that `_set_cs_params` is called at the beginning of the `check` method, but `_set_efield` is not.

We need to support users filling out UVBeam objects from scratch since there are not standard file formats.
