### ISSUE TITLE
Potentially change versioning in tests and/or package

### ISSUE THREAD

**Issue by plaplant** [RadioAstronomySoftwareGroup/pyuvdata#1187]
Some of our recent tests are failing on GitHub actions, seemingly because the version number is invalid according to [PEP440](https://peps.python.org/pep-0440/). We should be able to get tests going again by setting the `SETUPTOOLS_SCM_PRETEND_VERSION` environment variable, but we want to figure out if there is a deeper problem with how we're setting our version (e.g., because we include the branch name in our version). Further research is needed to figure out the best way forward.

**Comment by plaplant** [comment]
After digging into this a bit more, it seems like it's a known issue with `setuptools_scm>=7.0` (see https://github.com/pypa/setuptools_scm/issues/728). To get tests passing again, we could temporarily require an older setuptools_scm, and then lift this requirement when the issue is resolved.

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pypa/setuptools_scm/pull/730 will resolve this upstream

**Comment by plaplant** [comment]
@RonnyPfannschmidt thanks for the quick turnaround!

**Comment by RonnyPfannschmidt** [comment]
@plaplant the release is still stalled for another bugfix thats incoming hopefully this evening
