### ISSUE TITLE
Handling of lunar telescope data

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvdata#1192]
pyuvsim (and maybe one day, real telescopes!) can produce data from lunar surface.  pyuvdata should have a way to understand that telescopes are not on the earth (extra keyword "world" seems to be how pyuvsim handles it) but then also needs to have warnings/errors/updated methods for things that assume terrestrial observatory (e.g. phasing and uvw calculations)

**Comment by bhazelton** [comment]
on the 7/28/22 telecon we decided to add a `telescope_frame` parameter to the UVData and Telescope objects. The default should be `itrs` (the frame that astropy EarthLocation objects are defined in).

**Comment by aelanman** [comment]
The equivalent in `lunarsky` would be `MCMF`.

**Comment by bhazelton** [comment]
This has mostly been fixed, but I found one more problem in `utils.calc_app_coords` where the frame wasn't getting passed into `get_lst_for_time`.
