### ISSUE TITLE
Add support for antenna numbers greater than 2047

### ISSUE THREAD

**Issue by PyxieLouStar** [RadioAstronomySoftwareGroup/pyuvdata#1193]
The MWA has tile id numbers ranging from 0 to 32767, inclusive. Numbers greater than 2047 are not currently supported in pyuvdata.

**Comment by PyxieLouStar** [comment]
Currently we have two conventions for converting antenna numbers to baselines.
The first convention covers antennas numbered 0-255 inclusive, and has maximum baseline number 256^2.
The second convention covers antennas numbered 0-2047 inclusive, and has maximum baseline number 2048^2  + 256 ^2. 
A third convention is needed. A constraint is baseline numbers no larger than unsigned 64-bit integers. One option is to set the maximum baseline number as 2^64, which would then cover antennas numbered 0-4294967294 inclusive. Another is to follow the pattern of the first two conventions, in which the maximum baseline number would be 2147483648^2 + 2048^2 + 256^2, where each of the numbers in the sum are powers of two. In this case, the antenna range covered would be 0-2147483647 inclusive. 

I'm interested in opinions regarding these options.

**Comment by bhazelton** [comment]
To clarify, the difference in the options is whether or not the max antenna number is specified to be a power of 2. I don't think it's important that it is.
