### ISSUE TITLE
UVCal.read_fhd_cal() fails with actual antenna numbers

### ISSUE THREAD

**Issue by theo-kunicki** [RadioAstronomySoftwareGroup/pyuvdata#1221]
When an FHD calibration is created from a file which uses the "actual" antenna numbers, [11, 12, 13, ..., 1001, 1002, ..., 1071] of the MWA phase II array, instead of its antenna *indices*, [0, 1, 2, ..., 127], UVCal.read_fhd_cal() creates ant_array using antenna indices, and antenna_numbers using actual antenna numbers. This leads to a failed test and a "ValueError: All antennas in ant_array must be in antenna_numbers." Ideally, ant_array should be built with the real antenna numbers as well.

**Comment by bhazelton** [comment]
@PyxieLouStar maybe you and I can look into this, I think it's related to the way FHD handles antenna numbers/indices.

**Comment by PyxieLouStar** [comment]
Sounds good! I'll take a look
