### ISSUE TITLE
Change some long method signatures to require keyword arguments?

### ISSUE THREAD

**Issue by mkolopanis** [RadioAstronomySoftwareGroup/pyuvdata#1223]
python supports the `*` delineation in a method signature to require everything after to be keyword only (and `/` to signify everything before be positional only). Should we change some of our longer methods (e.g. `read`) to have the  keyword only arguments?

https://peps.python.org/pep-3102/

**Comment by steven-murray** [comment]
absolutely yes please

**Comment by bhazelton** [comment]
Ok, we'll do this in version 3.0. We don't currently know how to do a deprecation process for this, so doing it in a major version change is most appropriate.

**Comment by bhazelton** [comment]
Looking at this a bit and I have some questions. How aggressive do we want to be on this? Is this mostly for developers so we don't have to worry about changing parameter order, or is this mostly to protect users from accidentally passing parameters in the wrong order?

An example that I'm thinking about is the utility function `XYZ_from_LatLonAlt`. It can be confusing whether lat or lon comes first (although the function name should make this clear), so I could see requiring all the inputs to be passed by name. But there are only 3 inputs and I think this is pretty widely used, so this change might affect a lot of users. Thoughts?

**Comment by steven-murray** [comment]
IMHO that particular example should not be changed since the order of arguments is in the function name itself.

**Comment by bhazelton** [comment]
> IMHO that particular example should not be changed since the order of arguments is in the function name itself.

Thanks. What about `ENU_from_ECEF`, which has this signature: `ENU_from_ECEF(xyz, latitude, longitude, altitude, frame="ITRS")`. Should I make lat, lon, alt be passed by name?

**Comment by steven-murray** [comment]
I think so, yes. Because those are non-obvious.

**Comment by bhazelton** [comment]
fixed in #1333
