### ISSUE TITLE
Lunar phasing bugs

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvdata#1266]
Talking with @kartographer it looks like at least two potential lunar issues remain in the utils code.  I may not be describing these quite right but we can revisit.

(1) Line 2694 (and line 2700 in particular) seems to be using lunartopo as a drop in replacement for alt/az.  That's not right (I think).

(2) Line 2708 is using sidereal time from an astropy Time object, but it's likely not the correct sidereal time for the moon.

**Comment by kartographer** [comment]
So reading through the documentation for `lunarsky` a bit more deeply, my earlier concern about (1) may have just been a bit of nomenclature "mixing". I think topocentric is being used in a technically correct way, though `astropy` seems to differentiate between horizontal and topocentric frames (the latter seemingly referring to frames like TETE, which are RA/Dec but with diurnal abberation applied). It would be good to spot-check this, but I think the way it's written is okay.

But L2708 is definitely wrong.
