### ISSUE TITLE
Lunar telescope location round tripping bug

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyuvdata#1305]
When the telescope is set to be in the MCMF frame, it is not round tripped through UVH5. Also, there are no error messages if you try to write other file formats that do not support the MCMF frame.

**Comment by jpober** [comment]
Thinking about this some more, could we get this to work for uvfits as well?  It has a FRAME keyword in the antenna table.  According to AIPS Memo 117, "The value of the FRAME keyword shall be a string that identifies the coordinate system
used for antenna coordinates. At present, only one value of the FRAME keyword has been defined (’ITRF’),
although ’????’ is widely used to reflect ignorance."  So perhaps we could use that round trip MCMF?

**Comment by bhazelton** [comment]
This was addressed in #1329 and #1417
