### ISSUE TITLE
Minor mistake in tutorial doc

### ISSUE THREAD

**Issue by elillesk** [RadioAstronomySoftwareGroup/pyuvdata#1336]
In this chunk of the tutorial: https://pyuvdata.readthedocs.io/en/latest/uvdata_tutorial.html#uvdata-plotting

The call `plt.imshow(np.abs(UV.data_array[bl_ind, 0, :, 0])) ` fails because it has the wrong number of indices for the array. This is because the call `uvd = UVData.from_file(filename, use_future_array_shapes=True)` uses the use_future_array_shapes=True boolean, which drops the second index when loading  the data.

**Comment by bhazelton** [comment]
We run most of the code in the tutorial in our CI to catch these kinds of mistakes, but we've marked all the plotting code to not be run in that automated testing. Maybe we should revisit that decision to avoid these kinds of mistakes in the future.
