### ISSUE TITLE
Procedure to add telescopes to known_telescopes

### ISSUE THREAD

**Issue by telegraphic** [RadioAstronomySoftwareGroup/pyuvdata#1343]
Howdy, I've been using pyuvdata to convert data from SKA-low pathfinder telescopes -- the EDA2, AAVS2 and upcoming AAVS3 -- and was wondering the procedure to add these `telescopes.py`? Would I just issue a PR with the telescopes added to `KNOWN_TELESCOPES`? 

Thanks! (And thanks for pyuvdata)

**Comment by bhazelton** [comment]
Hi @telegraphic! We'd be happy to have those added, and yes a PR adding them to the `KNOWN_TELESCOPES` in `telescope.py` is the right way.

The main reason to have a telescope in `KNOWN_TELESCOPES  is to be able to update metadata in objects/files with telescope location and information. So if that metadata is present and accurate in your files already, having them in `KNOWN_TELESCOPES` is not really necessary, but we are happy to add any that are useful to the community.

**Comment by telegraphic** [comment]
Thanks @bhazelton , I'll hold off until we know exactly where they are! (I want to check GDA2020 -> WGS84 conversion). Going to close for now, will issue a PR if/when ready.
