### ISSUE TITLE
LST stringency issues

### ISSUE THREAD

**Issue by kartographer** [RadioAstronomySoftwareGroup/pyuvdata#1348]
Recently, we've been seeing a lot of warnings about LST accuracy when reading in SMA datasets into pyuvdata. After poking around a bit, this seems to have arisen following #1322, which effectively increased the stringency of the LST array to 1 mas accuracy (translating to 66.7 µs timing accuracy). The issue for the SMA -- or potentially any other array that does phase tracking in real time -- is that the LSTs calculated are based on IERS-predicted values of DUT (versus calculated after the fact), and the accuracy of those predictions are typically 0.25 ms per day extrapolated out (e.g., 4 days out from the last prediction would have ~1 ms accuracy).

Obviously the warnings aren't blocking data from being read in, but I think it's fair to call them spurious, and having lots of them raised seems suboptimal (for no other reason than it sets up a "boy who cried wolf" scenario). I think the core of the issue here is that one value is being used to address two separate questions -- the first being, "absent external information, are two values of LST the 'same' given some specified precision?", and the second being "is this value accurate/consistent with what we would expect given some knowledge of the outside world?" The 1 mas limit for the former makes sense, but I think for the latter it does not, and so I think it would be good to split this somehow in `check`. There may be other similar astrometry-based values (coordinates, uvws, etc.) where we might similarly consider splitting the stringency for precision vs accuracy.

**Comment by bhazelton** [comment]
I totally agree and have heard anecdotally that they're coming up a lot on other data sets as well.
