### ISSUE TITLE
utils.py has error in enu_to_ecef / enu_to_ecef on the moon

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvdata#1351]
There is an indexing error on lines 1508 & 1576 .  We *think* it should be [1,2,0] but aren't 100% sure. 

That said, the bigger issue is that this code is totally separate from the earth-based code.  We should let ECEF_from_ENU (in the cython) take a frame.  Right now, it has an if/else for earth vs moon, and the moon block has completely independent code.  To make this work, XYZ_from_lat_lon_alt will need to accept the frame and then use lunar values for things like gps_n etc.  It may be that we can get those values from lunarsky and, if we assume spherical symmetry, a lot of them become redundant.

**Comment by kartographer** [comment]
Just to provide a little example here, some "test code" from the current version of main (run in an python shell):
```
In [1]: import pyuvdata.utils as uvutils

In [2]: uvutils.ECEF_from_ENU([0.001, 0, 0], 0, 0, 0, frame="ITRS")
Out[2]: array([6.378137e+06, 1.000000e-03, 0.000000e+00])

In [3]: uvutils.ECEF_from_ENU([0.001, 0, 0], 0, 0, 0, frame="MCMF")
Out[3]: array([1.7371e+06, 0.0000e+00, 1.0000e-03])
```
A small East offset is behaving like I expected for ITRS (shifting along the Y-axis), but not for MCMF (shifts along the Z-axis).
