### ISSUE TITLE
Keep track of which redundancies were used in calibration

### ISSUE THREAD

**Issue by jsdillon** [RadioAstronomySoftwareGroup/pyuvdata#138]
In the new file format for calibration, we should include a way to store which groups of baseline pairs were treated as redundant when calibrating.

**Comment by bhazelton** [comment]
This can be added as an optional parameter if desired, an example is the total_quality_array.

**Comment by bhazelton** [comment]
@jsdillon Is this something you still are planning to work on or should we close the issue?

**Comment by jsdillon** [comment]
It's something I still think should be done, but it's quite low on my priority list. We haven't given much thought to how this is going to work in hera_cal yet.

**Comment by jsdillon** [comment]
Looking over my old issues, I think this is pretty irrelevant now. We can reconstruct what redundancies were used from the history pretty straightforwardly.
