### ISSUE TITLE
Ruff formatter

### ISSUE THREAD

**Issue by mkolopanis** [RadioAstronomySoftwareGroup/pyuvdata#1381]
We fought for black, isort, and many flake8 plugins. How do we feel about [ruff](https://github.com/astral-sh/ruff) as a linter?

For the flake8 plugins we currently use, we would only lose rst-docstrings and it looks like that is a complicate subject based on the thread I found where it is mentioned.

**Comment by bhazelton** [comment]
Sound good to me. I'm not sure that `rst-docstrings` is adding much. Separately, I find it very annoying that the flake8 plugins aren't versioned in the pre-commit yaml, so they can change suddenly with no pre-commit change.
