### ISSUE TITLE
Potential speedup for ERFA calls on large arrays

### ISSUE THREAD

**Issue by telegraphic** [RadioAstronomySoftwareGroup/pyuvdata#1389]
Hey all, not sure where exactly in the pyuvdata code this is relevant, but in my LST calculation code -- just before I call pyuvdata -- I realised (after profiling) that this:
```python
    lst_rad = t.sidereal_time('apparent').to('rad').value
    lst_rad = np.repeat(lst_rad,  uv.Nbls)
```
is a _lot_ faster than this:
```python
    lst_rad = np.repeat(lst_rad,  uv.Nbls)
    lst_rad = t.sidereal_time('apparent').to('rad').value
```
The reason, of course, is that in the latter the underlying ERFA code is working on `Nbls` more data. (In my example, `Nbls = 32896`!)

In this example it's pretty obvious, but I wonder if there are places in pyuvdata where code speed could be increased dramatically by only calculating for unique values. Essentially, I'm wondering if the overhead of calling `np.unique` before a calculation on an array of time/coords is worth it? It'd probably be pretty straightforward to write a generic function to do this.

I know there's overlap between the pyuvdata team and the matvis team, so perhaps some of y'all have already had a similar thought...

**Comment by steven-murray** [comment]
Indeed, I would expect this to be a lot faster! Not sure which way it's done in pyuvdata to be fair, but did you also see this is in matvis?

**Comment by david-macmahon** [comment]
Interesting.  I think the fast one computes a scalar `lst_rad` then repeats it to make a 1D array (that gets assigned to `lst_rad`), but I don't exactly understand how the second works.  It takes a scalar `lst_rad` (value doesn't matter?) and repeats it to make a 1D array (that gets assigned to `lst_rad`), but is it a numpy (or python?) convention that assigning a scalar RHS to an Array LHS does some sort of implicit broadcasting that evaluates RHS once per element on the LHS?  What is `t`?  Sorry for showing my python ignorance.

**Comment by telegraphic** [comment]
@david-macmahon the second one is just copying each value `N_bls` times, so expanding the array from having length `(N_timestep)` to `(N_timestep x N_bls)`. It's still 1D. So you calculate the exact same value `N_bls` times more than you need to.

@steven-murray I didn't see it in `matvis` -- but if I understand correctly, matvis works on matrices / tensors, so the data have a shape `[n_timesteps, n_bl, n_freq, n_pol]` or similar. So when computing a time array to correspond to the time axis, you just do it for `n_timesteps`. 

`pyuvdata` doesn't have this luxury, as it is essentially a table structure, with a different row for each baseline. This structure is needed to support BDA or cases where baselines are not in order. But in many cases (I think), the baselines are in lower or upper triangular order, so you have redundant entries in the arrays (FWIW, this also makes files much larger).

**Comment by david-macmahon** [comment]
So is the second one basically equivalent to this?
```python
    lst_rad = np.repeat(lst_rad,  uv.Nbls)
    lst_rad[0] = t.sidereal_time('apparent').to('rad').value
    lst_rad[1] = t.sidereal_time('apparent').to('rad').value
    lst_rad[2] = t.sidereal_time('apparent').to('rad').value
    # ...
```

**Comment by david-macmahon** [comment]
@telegraphic What do you mean by "so you have redundant entries in the arrays"?  The only redundancy I'm aware of are the cross polarizations of the autocorrelations, but those are also redundant in visibility arrays that have "baseline" as an axis.

**Comment by telegraphic** [comment]
Take this for example:
```python
from pyuvdata import UVData
uv = UVData()
# .... read data here with N_ant=256 and N_timestep=1 ...

uv.time_array

> array([2460278.66222212, 2460278.66222212, 2460278.66222212, ...,
       2460278.66222212, 2460278.66222212, 2460278.66222212])
```
This is an array with 32896 entries, all of which are the same. Same with 

```python
uv.phase_center_app_dec
> array([-0.46607409, -0.46607409, -0.46607409, ..., -0.46607409,
       -0.46607409, -0.46607409])
```

So calculations involving the phase center, or time/LST, will be computed 32896x times if these arrays are used, when they only need to be computed once!

**Comment by kartographer** [comment]
Hey @telegraphic -- so at least as far as the main LST (`utils.get_lst_for_time`) and astrometry (`utils.calc_app_coords`) calculators, this is indeed what's done. E.g., in `get_lst_for_time`:

```
    jd, reverse_inds = np.unique(jd_array, return_inverse=True)
...
    times = TimeClass(jd, format="jd", scale="utc", location=site_loc)
...
    gast_array = erfa.gst06a(times.ut1.jd1, times.ut1.jd2, times.tt.jd1, times.tt.jd2)
    sp = erfa.sp00(times.tt.jd1, times.tt.jd2)
    lst_array = np.mod(gast_array + sp + site_loc.lon.rad, 2.0 * np.pi)[reverse_inds]
```

There are a few other places where I've tried to pay this same trick above -- particularly with duplicate times -- although I admit that I've mostly focused on this in the few utilities that I've touched (and even then, there may be some low-hanging fruit that I've just missed...).

**Comment by telegraphic** [comment]
@kartographer excellent stuff, in that case I'm marking this case closed 👍
