### ISSUE TITLE
Add new metadata to UVCal and UVData objects to track the polarization normalization

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyuvdata#1441]
There are two potential approaches:

- Add a new optional UVParameter to the objects, maybe called `polarization_normalization`, to track this. The options should be `"sum"` and `"average"` to indicate whether the two polarizations should be averaged or summed to get to Stokes I. It shouldn't be set for uncalibrated data or for pseudo-stokes polarizations (unless you're doing something very strange).

- Fold this into the vis_units parameter, by indicating `'Jy (sum)'` or `Jy (average)'`. `Jy` would still be allowed.

Note: we'd only do one of the above options, interested in community feedback about which one to implement.

When applying a calibration to a UVData object, if this metadata is set on the UVCal object it should be propagated to the calibrated UVData object.

**Comment by jsdillon** [comment]
This seems reasonable to me.

**Comment by bhazelton** [comment]
> This seems reasonable to me.

@jsdillon Do you have a preference between the two options?

**Comment by jsdillon** [comment]
Sorry, I was confused. I thought the idea was to do both.

I think Option A feels more "right" to me, but I'm open to both.

**Comment by rlbyrne** [comment]
I prefer the first option, to keep `vis_units` a real unit. I think the second option could also get confusing because there is nothing in the parameter or value to connect "sum" and "average" to polarization.

**Comment by bhazelton** [comment]
Done in #1455
