### ISSUE TITLE
CI benchmarking

### ISSUE THREAD

**Issue by mkolopanis** [RadioAstronomySoftwareGroup/pyuvdata#1452]
This action looks really cool. I think with some minimal amount of effort we could set up some automated benchmarks to run for PRs. Make it require all actual tests to run before attempting too. 

This could be pretty useful especially when inevitably I end up going back and attempting to re-work some of our compiled extensions.

Could also be good for beam related things since performance is important there.

https://github.com/benchmark-action/github-action-benchmark

**Comment by bhazelton** [comment]
We should definitely do this!

**Comment by bhazelton** [comment]
@mkolopanis did #1463 finish this?

**Comment by mkolopanis** [comment]
Hm finish is a strong word :laughing: but i definitely think we're off to a good start. probably worth closing I'd say and as anyone feels the need to add more it is easy to do.
