### ISSUE TITLE
somehow deal with CASA importuvfits combining multiple sub-arrays when converting from .uvfits -> .ms

### ISSUE THREAD

**Issue by anguta** [RadioAstronomySoftwareGroup/pyuvdata#168]
multi_subarray.uvfits -> multi_subarray.ms via CASA's (4.7.2) importuvfits function appears to have a single sub-array. For this reason, test_breakReadMS() in test_ms.py is commented out.

**Comment by bhazelton** [comment]
This is out of date and may not be an issue.
