### ISSUE TITLE
Add support/consistency for "East" and "North" polarization

### ISSUE THREAD

**Issue by adampbeardsley** [RadioAstronomySoftwareGroup/pyuvdata#173]
HERA has adopted "East" and "North" polarization scheme, whereas uvfits and most of radio astronomy, uses "X" and "Y". We need to reconcile these things.

**Comment by bhazelton** [comment]
We will use the x_orientation parameter as in UVCal to support this. It should be added to UVData as an optional parameter. No acceptable values should be listed, just examples in the description. Consider adding it to UVBeam.

**Comment by bhazelton** [comment]
Fixed with latest PR.

**Comment by dannyjacobs** [comment]
This fix does not appear to allow us to index by "EE", even if x_orientation is set.   If that is correct then we should add that capability to k2inds. 
https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/c1ef8f781367ef4aed08c0c22e0ebbe74d17ec2e/pyuvdata/uvdata.py#L2649
