### ISSUE TITLE
develop alternate method for extracting git information

### ISSUE THREAD

**Issue by plaplant** [RadioAstronomySoftwareGroup/pyuvdata#219]
The git command used to capture version information (in `construct_version_info` in `version.py`) requires relatively recent versions of git. Specifically, it requires the `-C` flag (for executing the git command as if it had been run in the specified directory). For git versions at least as old as 1.8.3 (could also include versions newer than that), this command fails. The result is that version information is not stored in pyuvdata objects. We should find an alternative method for extracting the git information, so that we are able to get it even when the system has older git versions installed.

**Comment by bhazelton** [comment]
Closing, nobody uses a git version that old anymore.
