### ISSUE TITLE
Release memory after reading (miriad) files

### ISSUE THREAD

**Issue by adampbeardsley** [RadioAstronomySoftwareGroup/pyuvdata#227]
To summarize a long discussion on Slack:
We noticed when reading large miriad files (and possibly other file types, haven't tested yet), the python instance hangs onto about 2x memory than the actual UVData object. For example, when reading a 1GB file, the UVData object ends up being ~2.5GB (`nsample_array` is larger in memory than on disk... another issue), but top shows python using >~4GB memory. Even after explicitly deleting the UVData object, python keeps ~2.3 GB. 
@plaplant did a profiling demonstration:
```
Line #    Mem usage    Increment   Line Contents
================================================
     5   84.277 MiB    0.000 MiB   @profile
     6                             def test_fake_data():
     7   84.277 MiB    0.000 MiB       fn1 = '/home/plaplant/data/2457755.11978.xx'
     8   84.277 MiB    0.000 MiB       fn2 = '/home/plaplant/data/2457755.20333.xx'
     9
    10   84.324 MiB    0.047 MiB       uvd1 = UVData()
    11   84.328 MiB    0.004 MiB       print("reading {}...".format(fn1))
    12 4453.570 MiB 4369.242 MiB       uvd1.read_miriad(fn1)
    13 4453.574 MiB    0.004 MiB       print("uvd1 data size: ", uvd1.data_array.shape)
    14
    15 4453.574 MiB    0.000 MiB       uvd2 = UVData()
    16 4453.574 MiB    0.000 MiB       print("reading {}...".format(fn2))
    17 6571.598 MiB 2118.023 MiB       uvd2.read_miriad(fn2)
    18 6571.598 MiB    0.000 MiB       print("uvd2 data size: ", uvd2.data_array.shape)
    19
    20 6571.598 MiB    0.000 MiB       print("combining files...")
    21 12823.281 MiB 6251.684 MiB       uvd = uvd1 + uvd2
    22 12823.281 MiB    0.000 MiB       print("total data size: ", uvd.data_array.shape)
    23
    24                                 # delete the objects
    25 10706.738 MiB -2116.543 MiB       del uvd1
    26 8590.195 MiB -2116.543 MiB       del uvd2
    27 2307.660 MiB -6282.535 MiB       del uvd
    28
    29 2307.660 MiB    0.000 MiB       return
```

Google has led us to believe this is actually a "feature" of python. The memory is released within python, but not necessarily available to the os. The reasoning, as I understand it, is that python earmarks this memory for certain types of objects, in case you want to use it again. It appears there is no way to tell python you really really don’t want that memory again. 

The best suggestion I've found so far is to launch a child process to do the reading task. When the process returns the memory should be freed to the os.

I wrote a small script to test the child process idea:
```
from multiprocessing import Process, Queue
import pyuvdata
import time


def func(q, fname):
    uv = pyuvdata.UVData()
    uv.read_miriad(fname)
    q.put(uv)

if __name__ == '__main__':
    queue = Queue()
    p = Process(target=func, args=(queue, '/data4/beards/tmp/PaulsData/2457755.11978.xx/'))
    p.start()
    p.join()
    uv1 = queue.get()
    print('waiting... check me in top!')
    time.sleep(10)
    print('reading second file to check against')
    uv2 = pyuvdata.UVData()
    uv2.read_miriad('/data4/beards/tmp/PaulsData/2457755.11978.xx/')
    print('are objects equal?')
    print(uv1 == uv2)
```
This script errors: `IOError: bad message length`. So apparently processes can only handle passing objects up to some size. sigh.

More googling gives two suggestions: pickling the data to hand over, or creating shared memory between the two processes. The former will result in a slow step to hand over the data, and the latter will be slow to read/write to the memory. But I'm not sure that's a limiting factor within the read functions, so I'll probably try that first.

More to come...

**Comment by bhazelton** [comment]
It does not appear that we can fix this, it's intrinsic to python's memory management. You can do selects on read to minimize the impact of this.
