### ISSUE TITLE
Add tutorial examples for UVCal to show full functionality

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyuvdata#256]
Tutorial should cover:
--  ~__add__ method (there is a tutorial example on that for UVData)~
-- convert_to_gain method

**Comment by bhazelton** [comment]
the add method is done.

**Comment by theo-kunicki** [comment]
I'm taking a stab at this.

**Comment by bhazelton** [comment]
Done in #750
