### ISSUE TITLE
Include add_uvws.py to scripts for backwards compatibility 

### ISSUE THREAD

**Issue by jaguirre** [RadioAstronomySoftwareGroup/pyuvdata#258]
While we're not using it going forward for new HERA data due to uvw's in the data files, we need a canonical way to add uvw to HERA-19 and PAPER, among others, to make compatible with pyuvdata and to convert to other formats.  Can the version from hera_sandbox/dcj be pulled in?

**Comment by bhazelton** [comment]
This can be done using the `set_uvws_from_antenna_positions` method on pyuvdata.
