### ISSUE TITLE
imaging files concatenated by `pyuvdata` rotates image?

### ISSUE THREAD

**Issue by nkern** [RadioAstronomySoftwareGroup/pyuvdata#296]
When I image a 10-minute HERA-47 Miriad file, my images appear as I expect. If, however, I concatenate a series of 10-minute Miriad files using `pyuvdata` and image that file, my images appear slightly rotated (see below). This rotation gets worse the more files I concatenate, leading me to think it is perhaps a phasing issue? One thing that happens in the process of getting a Miriad file to a CASA MS is converting to `uvfits` which phases the whole dataset to the first time integration.

As I said, I'm not sure if this is a `pyuvdata` problem or a problem in my imaging scripts, so if someone can try to duplicate this with their own imaging scripts, that would be appreciated.

![gleam02_1file_concat](https://user-images.githubusercontent.com/4307358/35997600-d2aaa554-0cce-11e8-8570-fc1cfc69750d.png)
^ Image of a GLEAM 02h source on a single 10-minute Miriad file

![gleam02_6file_concat](https://user-images.githubusercontent.com/4307358/35997541-a21cd542-0cce-11e8-9631-f7cf3aa4c834.png)
^ Image of the same source having concatenated 6 time-contiguous Miriad files w/ `pyuvdata`

**Comment by bhazelton** [comment]
How did you phase the files?

**Comment by nkern** [comment]
yeah, good point.

This rotation gets worse the more files I concatenate, leading me to think it is perhaps a phasing issue? One thing that happens in the process of getting a Miriad file to a CASA MS is converting to uvfits which phases the whole dataset to the first time integration.

**Comment by nkern** [comment]
I do the Miriad -> uvfits via the `pyuvdata.miriad_to_uvfits.py` script

**Comment by bhazelton** [comment]
yes, but you can phase the files to a specific location if you'd like, rather than just letting it default to the first time sample

**Comment by nkern** [comment]
well, in CASA, I do a `fixvis`, which should phase the data to the location I want. is there some discrepancy between the phasing algorithm in `pyuvdata` and CASA?

**Comment by bhazelton** [comment]
So after reading in the miriad files, you can use the `phase_to_time` or `phase` methods before calling write_uvfits.

It is possible that there is a discrepancy. CASA is known to have some phasing issues. pyuvdata is not perfect either, partly because we have struggled to find reference files to test against, but we believe it is good to better than an arcsecond. See issue #148

**Comment by nkern** [comment]
ok, i'll try that and see if it fixes the problem and let you know

**Comment by bhazelton** [comment]
Thank you, I'm definitely interested. This may be a very good thing to help us figure out residual phasing problems.

**Comment by bhazelton** [comment]
I need to refresh myself on the details, but there is an option in CASA that only applies a phase to the visibilities but does not change the UVWs which is fundamentally not what is generally meant by phasing in radio astronomy.

I believe that there is also an option which is supposed to properly change the visibilities and uvws together but there was a bug in that code at least as of a year or so ago. @dannyjacobs may know more about this.

**Comment by nkern** [comment]
indeed, seems to have fixed the issue
![gleam02_6file_concat_w_phase_time](https://user-images.githubusercontent.com/4307358/35998394-4c733ffc-0cd1-11e8-84f7-053e3e7d303f.png)
^ Image of GLEAM 02h source having concatenated 6 time-contiguous Miriad files, phased to the source time, and then written out to uvfits and passed through CASA

**Comment by nkern** [comment]
my `fixvis` call in CASA is
```
fixvis(msin, msin, phasecenter=fixdir)
```
which based on the CASA doc seems re-calculate the UVW array...

**Comment by bhazelton** [comment]
Excellent! Easier than I was worried it'd be. Should we close the issue?

**Comment by bhazelton** [comment]
Just saw your last comment. This bears looking more into I think.

**Comment by nkern** [comment]
well, not sure just yet: I think we have gotten used to using `miriad_to_uvfits.py` as a general purpose Miriad -> uvfits tool, and what we are seeing now is that for longer integration files we can't use that script... perhaps we can add a "jd_time" argument to `miriad_to_uvfits.py` that will optionally phase data to that input before writing to uvfits?

**Comment by bhazelton** [comment]
We may just rediscover a known CASA problem, but in theory the information in the FITS file should tell CASA where the data are currently phase.

**Comment by nkern** [comment]
that should solve problems on my end at least..

**Comment by bhazelton** [comment]
I'm definitely in favor of improving the script, why don't you add what you think is needed and make a PR? Maybe make some options so people can do different things...

**Comment by nkern** [comment]
sure thing!

**Comment by bhazelton** [comment]
But I'm also curious about the underlying problem. If CASA is getting the right info, and barring any bugs, it should be able to rephase the data as you'd like.

**Comment by nkern** [comment]
agreed. I think someone should try to duplicate this result with their own CASA imaging scripts just to ensure its not something I'm doing by accident... :)

**Comment by bhazelton** [comment]
Fair enough. I think your best bet there is probably @KingsleyWeb

**Comment by bhazelton** [comment]
If you're up for another test @nkern, I'd love to try doing the pyuvdata steps in another order to make sure the order doesn't matter: First read in all the miriad files (read_miriad can be passed multiple files) and then phase the final object once.

Also, as a clarification, did the original script phase each file to it's own first time before combining the files? That would explain the problem but should have raised an error in pyuvdata

**Comment by nkern** [comment]
@bhazelton that is exactly what I did for that third image above: I read in 6 files at once with `uvd.read_miriad(['fname1', 'fname2', ...])`, then used `uvd.phase_to_time(<source_JD>)`, then wrote it out as `uvd.write_uvfits(<output_fname>, spoof_nonessential=True)`, then passed that `uvfits` file through my CASA pipeline.

**Comment by bhazelton** [comment]
great, thanks!

**Comment by bhazelton** [comment]
@nkern should we close this issue or is there still work to be done on it?

**Comment by bhazelton** [comment]
@nkern should this issue still be open?

**Comment by bhazelton** [comment]
closing now because of recent phasing improvements.
