### ISSUE TITLE
Check for single source/subarray files

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvdata#32]
We only support single source files, but we don't check to ensure the input file is single source

**Comment by jpober** [comment]
Now implemented in read_miriad

**Comment by jpober** [comment]
Should also error on files with multiple subarrays in read_uvfits

**Comment by jpober** [comment]
TODO: add unit tests with multi-source/multi-subarray files

**Comment by bhazelton** [comment]
track this with test coverage.
