### ISSUE TITLE
verbose option for read_miriad

### ISSUE THREAD

**Issue by carinacheng** [RadioAstronomySoftwareGroup/pyuvdata#330]
Is it possible to have a verbose=True option that prints out the files that are being read in real-time? Digging around a little, it doesn't seem straightforward to do it in AIPY since it's MIRIAD under-the-hood, but this feature would be nice.

**Comment by bhazelton** [comment]
@carinacheng is this still something you want?

**Comment by carinacheng** [comment]
Nah, it's fine. Thanks for checking!
