### ISSUE TITLE
reading uvfits files (w/o unphase_to_drift) phases look weird

### ISSUE THREAD

**Issue by nkern** [RadioAstronomySoftwareGroup/pyuvdata#356]
if you load a uvfits file into a `UVData` object and don't run `unphase_to_drift` the phases look weird: weird in that they don't look like they are phased to a particular time or point on the sky. @AaronParsons and I are just wondering if @bhazelton has any insight as to why that might be the case? In short, we want to make sure that this isn't because of an error in the way phasing is applied, or in some metadata variable..

![uvfits_omni_mdl](https://user-images.githubusercontent.com/4307358/40257940-d7a214b0-5aa4-11e8-9ee5-ae87b94c863a.png)
^ UVFITS waterfall w/o `unphase_to_drift`

![uvfits_omni_mdl_unphased](https://user-images.githubusercontent.com/4307358/40257957-e02c5ae6-5aa4-11e8-87ec-61cfc4c0812b.png)
^UVFITS waterfall w/ `unphase_to_drift`

**Comment by bhazelton** [comment]
@nkern Sorry for the delayed response. The phasing (and unphasing) in pyuvdata is known not correct in detail, although it appears to make reasonable images of HERA data (see the Chris' and the ASU team's efforts). It is based on older aipy phasing code, although it may have been modified from that as well.

I'm not entirely sure what is going on in your plots, but I have been working on a complete revamp of the phasing & unphasing code. I believe that code is now correct and I have tested it against MWA files and get good matching (to a few cm in u, v, w coordinates).

That new code is available on the `uvdata_time_array_fix` branch and in PR #287 if you would like to experiment with it. One caveat is that unphasing data that were phased with the previous code version will not get the right answer. If that is something we want to support, I can probably add some backwards compatibility code to do that fairly easily.

**Comment by bhazelton** [comment]
@nkern The new phasing code has now been merged into master. Note that if you are working with files that were phased with the old code that you now want to unphase you should set the `use_ant_pos` keyword to true when you unphase.

**Comment by bhazelton** [comment]
We're closing this now, you can re-open it if there's still a problem.
