### ISSUE TITLE
Selecting one visibility with read_miriad

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvdata#361]
Looks like there is a bug trying to use read_miriad and having syntax that only selects one visibility.  For example, using the atca_miriad test file and trying

`uvd.read_miriad('atca_miriad',ant_str='0_1')

returns an error.  But

`uvd.read_miriad('atca_miriad',ant_str='0_1,1_2')

works and returns an object with two visibilities.

**Comment by bhazelton** [comment]
@nkern can you take a look at this?

**Comment by nkern** [comment]
Ah, I think this is a bug that I incidentally fixed in a separate branch (`read_miriad_metadata`) that I discovered totally separately! The bug I fixed is when you try to load in a single time and single baseline. So @jpober if that `atca_miriad` file has only a single time, then your first statement would be fixed by this branch. If it doesn't, then I don't know immediately what the problem is and I'll have to take a look.

**Comment by jpober** [comment]
The file indeed has one time, but many frequencies.  If one time, one baseline, many frequencies causes the bug, then it indeed sounds like the same thing.  Has read_miriad_metadata been merged into master, i.e., has this been fixed?

**Comment by bhazelton** [comment]
Yes it was just merged in about an hour ago.

**Comment by jpober** [comment]
Reading a single baseline no longer errors, but it does return two warnings:

Mean of empty slice.
invalid value encountered in double_scalars

The resulting object though has a populated data_array with non-zero values.  Not really sure what to make of this...

**Comment by bhazelton** [comment]
that's exciting. Can you illuminate this @nkern?

**Comment by nkern** [comment]
Yeah, I feel like I see those warnings a lot in various contexts and have started to just zone them out b/c I haven't seen anything wrong with the data.. but we could try to isolate where those warnings are originating from and figuring out their origin and, if they are innocuous, silencing them

**Comment by bhazelton** [comment]
Where are we on this issue?

**Comment by jpober** [comment]
We still see those warnings as far as I know.  No idea if they are just a nuisance or if there is some subtle compromising of the data.

**Comment by bhazelton** [comment]
let's add a test that triggers this warning and verify that the visibility values are correct.

**Comment by jpober** [comment]
This warning is no longer reproducible on the main branch.
