### ISSUE TITLE
partial I/O for `UVCal`

### ISSUE THREAD

**Issue by nkern** [RadioAstronomySoftwareGroup/pyuvdata#364]
It would be nice to have partial I/O capabilities for `UVCal` objects and `calfits` files. Just FYI, I did a line-profile on `UVCal.read_calfits` on a decently large file (~80 MB), and ~60% of the time was spent on line 434
```
self.gain_array = data[:, :, :, :, :, 0] + 1j * data[:, :, :, :, :, 1]
```
and 20% of the time was spent on lines 394-395
```
while 'HISTORY' in hdr.keys():
    hdr.remove('HISTORY')
```

**Comment by bhazelton** [comment]
Select on read is now supported for CalH5 files. Partial write is not yet supported on CalH5, but could be added if needed. Select on read is not yet supported on CalFITS.

 I think I'll close this issue but another can be opened as needed for those specifically.
