### ISSUE TITLE
Return indices when `get_data` is called

### ISSUE THREAD

**Issue by plaplant** [RadioAstronomySoftwareGroup/pyuvdata#369]
A nice feature to have of the `get_data` function is to return the indices corresponding to the data. The indices can then be used for updating the data values, or for getting the corresponding flags without having to redo the calculation.

The ideal goal would be to return a slice object rather than the list of indices, so that we can efficiently access the data and flag arrays.

**Comment by jsdillon** [comment]
This and #370 should probably be handled at once.

**Comment by jsdillon** [comment]
As I commented on #370, 

> We've gone in a different direction in hera_cal for dealing with the problems that gave rise to this issue (see HERA-Team/hera_cal#331), so I no longer feel like we need this. We can close this unless @adampbeardsley feels like he still wants to add it for pyuvdata.
