### ISSUE TITLE
Add "sliceability" attribute to UVData object

### ISSUE THREAD

**Issue by plaplant** [RadioAstronomySoftwareGroup/pyuvdata#370]
When `get_data` is called, a check is first done to see if the requested data has a regular stride along the `blt` axis. This can be expensive for repeated calls, so we should add an attribute to a UVData object that starts out uninitialized. When `get_data` is called the first time, the check can be done, and the attribute set so that it doesn't have to be done on subsequent calls to `get_data`.

**Comment by jsdillon** [comment]
We've gone in a different direction in hera_cal for dealing with the problems that gave rise to this issue (see https://github.com/HERA-Team/hera_cal/pull/331), so I no longer feel like we need this. We can close this unless @adampbeardsley feels like he still wants to add it for pyuvdata.
