### ISSUE TITLE
convenience method for BDA handling: resampling averaged baselines

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyuvdata#428]

**Comment by jsdillon** [comment]
As discussed at CHAMP, it would be nice it we rephase appropriately when we up- and down-sample.

**Comment by bhazelton** [comment]
upsampling: copy the visibility (maybe divide by number of samples?), update integration time & nsamples & baseline/time array. Possibly with memory mapping (as an option)?

downsampling: average or sum the visibilities, update integration time & nsamples  & baseline/time array
