### ISSUE TITLE
bug with integration_time when adding polarizations w/ diff integration time

### ISSUE THREAD

**Issue by nkern** [RadioAstronomySoftwareGroup/pyuvdata#433]
Recently, the `UVData.integration_time` was broadcasted to a vector from a scalar, but that vector only spans the `blts` axis. It should in principle extend to the `polarization` axis as well. One can, for eaxmple, add two `UVData` objects w/ different `integration_time` vectors and different polarizations, and one is `integration_time` is chosen over the other, but the polarizations are added just fine, which is a bug.

**Comment by nkern** [comment]
This bug also extends to any axis along which we can add `UVData` objects, whose axis is not included in `integration_time`. Therefore, this is also a bug when adding `UVData` objects with different frequencies. One way to eliminate this is to raise a Warning when adding across frequency with variable integration_time vectors.

**Comment by nkern** [comment]
In addition, now that `integration_time` is no longer a scalar, there should be a `get_integrations` method that does the `blts` slicing for the user.

**Comment by plaplant** [comment]
I agree that this is probably a bug. There is a set of "compatibility parameters" that are required to be the same before two UVData objects are added, but there are certain bits of metadata (such as integration_time, time_array, uvw_array, and a few others) that _should_ be checked if the objects are not being added along the blt axis which are not being checked right now. @bhazelton what do you think about checking additional metadata if objects aren't being combined along the blt axis?

Also, what are you envisioning the `get_integrations` function would do? You can retrieve the integration time for a given data point using array indices the same way you would get the time or LST, and you can get a list of all integration times in the data doing something like `np.unique(self.integration_time)`. Are there other use cases you think should be addressed?

**Comment by nkern** [comment]
Well, there isn't a good one-liner to get that info, so I guess in lieu of a `get_integrations` function, I'll just make a `get_blts_inds` function that does the unordered baseline-time slicing for you, which you can then stick into any array of len blts (essentially what `get_times` does, but generalized such that any array can be used). I'll put it into the PR I have open now

**Comment by bhazelton** [comment]
I think it's an oversight that additional metadata wasn't being checked when objects are combined along other axes and we should fix it.

**Comment by adampbeardsley** [comment]
I'm just catching up on things from when I was on holiday. @nkern there is a function, `antpair2inds`, which takes an antenna pair and returns the blt indices corresponding to that pair. Is that what you were proposing for `get_blts_inds`?

**Comment by bhazelton** [comment]
@adampbeardsley please take a look at PR #432, I'd really like your input there.

**Comment by adampbeardsley** [comment]
Yup, that's the PR that brought me over here. Just posted a comment.
