### ISSUE TITLE
healpix beam interpolation 

### ISSUE THREAD

**Issue by anguta** [RadioAstronomySoftwareGroup/pyuvdata#441]
uvbeam currently only supports az/el grid interpolation but not healpix. Healpix interpolation can quickly be implemented with bi-linear interpolation that is already built into healpy.

**Comment by bhazelton** [comment]
done in #547

**Comment by bhazelton** [comment]
Note: interpolating in Healpix may not be what you want to do for current HERA beam models. They originate in regularly gridded az/za and are interpolated to get to healpix. Further interpolating the healpix beams will accumulate interpolation errors.
