### ISSUE TITLE
rotecef_positions doesn't seem to be able to handle the output from ecef_positions.

### ISSUE THREAD

**Issue by david-deboer** [RadioAstronomySoftwareGroup/pyuvdata#448]
In [3]: h.get_cminfo_correlator()
[[ 5109312.3250626   5109307.00698963]
 [ 2005116.94634363  2005130.55176796]
 [-3240024.0873978  -3240024.03444468]]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-e78d4dc987a8> in <module>()
----> 1 h.get_cminfo_correlator()

/Users/ddeboer/Documents/ubase/Projects/HERA/ops/hera_mc/hera_mc/sys_handling.py in get_cminfo_correlator(self)
    261         print(ecef_positions.T)
    262         rotecef_positions = uvutils.rotECEF_from_ECEF(ecef_positions.T,
--> 263                                                       cofa_loc.lon * np.pi / 180.)
    264 
    265         return {'antenna_numbers': stn_arrays.antenna_number,

/Users/ddeboer/miniconda3/envs/python2/lib/python2.7/site-packages/pyuvdata-1.3.1-py2.7-macosx-10.6-x86_64.egg/pyuvdata/utils.pyc in rotECEF_from_ECEF(xyz, longitude)
    174                            [np.sin(angle), np.cos(angle), 0],
    175                            [0, 0, 1]])
--> 176     return rot_matrix.dot(xyz.T).T
    177 
    178 

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

**Comment by bhazelton** [comment]
Ah, take out the transpose:
` uvutils.rotECEF_from_ECEF(ecef_positions, cofa_loc.lon * np.pi / 180.)`
