### ISSUE TITLE
overlapping data bug when reading in a list of files

### ISSUE THREAD

**Issue by plaplant** [RadioAstronomySoftwareGroup/pyuvdata#455]
We've seen some strange issues when passing in a list of miriad files to read, which triggers the in-place-add feature to combine them into a single UVData object. In some cases, the error `ValueError: These objects have overlapping data and cannot be combined` is raised, even though there should not be overlapping data. This was seen by @ianmalcolm to happen for some IDR2 data (when combining all 4 polarizations from a single time) and by me with some old HERA-19 data (when combining data from adjacent times). I'll try to come up with a minimal working example to reproduce the bug and follow up here.

**Comment by plaplant** [comment]
Okay, I've been able to reproduce this bug for my case (reading in a list of two sets of 4-pol files from different times), and I think there's an implicit assumption about the blt x polarization metadata broadcasting. The way we check to see if there are overlapping data before adding two UVData objects together is to do:

```python
        # Check we don't have overlapping data
        both_pol = np.intersect1d(
            this.polarization_array, other.polarization_array)
        both_freq = np.intersect1d(
            this.freq_array[0, :], other.freq_array[0, :])
        both_blts = np.intersect1d(this_blts, other_blts)
        if len(both_pol) > 0:
            if len(both_freq) > 0:
                if len(both_blts) > 0:
                    raise ValueError('These objects have overlapping data and'
                                     ' cannot be combined.')
```

This is fine for combining multiple polarizations from the same time slice, or the same polarization from different time slices. However, it fails if I already have multiple polarizations from 1 time, read in a single polarization from one time, and then try to read another polarization from that second time. I've got an image in my head like a square:

```
        pol1   pol2
      ---------------
time1 |  xx  |  yy  |
      ---------------
time2 |  xx  |  yy  |
      ---------------
```
Suppose that I already have time1-pol1, time1-pol2, and time2-pol1 in a single UVData object, and I try to combine it with time2-pol2. I have overlapping polarizations (because 'yy' is common to both), and the overlapping baseline-times (because time2-pol1 has the same blts as time2-pol2), even though there isn't data present for time2-pol2. (Technically there _is_ data present because what happened behind the scenes is that the data_array for missing pol/time combos was filled out with zeros when time2-pol1 was read in, to make sure we don't have ragged arrays.) However, it seems like this shouldn't happen if the user has requested that data to be read _eventually_ as part of a single `read` call.

I'm not sure the best way to fix this going forward. I got around this personally by first combining all 4 polarizations for each time, then combining the times together, and that went just fine. Perhaps we want to address this bug as part of the push to make the `__add__` operation faster/smarter in #406. Perhaps we should discuss this at the next pyuvdata telecon?

**Comment by bhazelton** [comment]
This is a corner case that I think we were aware might come up at some point, and I think it may exist for more combinations beyond just pol and time. I like your diagram, and I think you're exactly right, the problem is that by adding files one at a time we always end up in the situation of having 3 of your 4 blocks, then having to fill in the 4th with zeros and then having overlapping data. Fixing that problems is a bit hard because you have to be clever about what order you add the objects together.

One option would be to test if all the 'overlapping' data that already exist in the object are zeros, and then just overwrite them if that's the case.

**Comment by bhazelton** [comment]
Apparently there is an option to spline to make the boundary conditions periodic! This is probably the right way forward here.
