### ISSUE TITLE
document the new redundant baseline functionality in the tutorial

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyuvdata#457]
Need some examples of how to use it in the tutorial.

@aelanman can you take this on?

**Comment by aelanman** [comment]
Sure. I'm also adding the option to include cases when the baseline has to be reversed to be redundant. I'm now getting the same redundancies as hera_cal. I'll include the documentation update with this new branch.

**Comment by bhazelton** [comment]
Great!
