### ISSUE TITLE
method to add matched visibilities between 2 objects

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyuvdata#501]
e.g. to combine simulated EoR/foreground/noise visibilities.

Needed for pyuvsim: RadioAstronomySoftwareGroup/pyuvsim#28

**Comment by bhazelton** [comment]
This same method should also be able to difference visibilities e.g. to create residuals from dirty & model or to simply compare different visibility sets.

**Comment by jaguirre** [comment]
yes, this would move validation Step -1 along (comparing simulations against a reference sim)

**Comment by adampbeardsley** [comment]
What needs to be done?
- check metadata
  - baselines, phasing, time, frequencies, pols, etc
- Add/subtract the visibilities
- inplace option
- write tests

**Comment by bhazelton** [comment]
Brainstorming ideas for the name of this method (which can't be add):
`join`
`add_visibilities`

**Comment by jaguirre** [comment]
I don’t love join – too much like concatenate.

`add_visibilities` is good, or even `add_data`.

James Aguirre
Associate Professor
Department of Physics and Astronomy
University of Pennsylvania
David Rittenhouse Laboratory 4N4b
209 South 33rd Street Philadelphia, PA 19104
(215) 898-9596 (office)
(215) 898-9646 (lab)
jaguirre@sas.upenn<mailto:jaguirre@sas.upenn>.edu
http://www.sas.upenn.edu/~jaguirre/

**Comment by bhazelton** [comment]
What about `combine_data`? That makes it match better to the proposed option to either add or subtract the data.

**Comment by mkolopanis** [comment]
`combine_data_arrays_with_addition_function` and `combine_data_arrays_with_subtraction_function` :laughing:

**Comment by jaguirre** [comment]
How about combine_data and it takes an optional argument to multiply each data set by a scalar?

Sent from my iPhone

On Oct 17, 2019, at 8:34 PM, Matthew Kolopanis <notifications@github.com<mailto:notifications@github.com>> wrote:


combine_data_arrays_with_addition_function and combine_data_arrays_with_subtraction_function 😆

**Comment by bhazelton** [comment]
Or just a keyword that is `add` or `subtract`. Do you anticipate wanting something beyond 1 and -1?

**Comment by jaguirre** [comment]
Actually, maybe ... if you think you need to rescale them onto a common calibration ... perhaps this is getting into too much of not-commonly-needed scenario.  But it was something I was thinking about ...

**Comment by adampbeardsley** [comment]
How should we handle objects with different flag arrays?

**Comment by bhazelton** [comment]
For now the plan is to require identical weights and flags. This isn't something that is likely to be used with real data -- you never have 2 sets of real data with identical metadata.

**Comment by bhazelton** [comment]
@jaguirre That seems like a really niche and unusual situation, especially since this is unlikely to be used on real data. I'd suggest that in the case you can just multiply the data arrays by some factor before adding or differencing them.

**Comment by ntk688** [comment]
I figure we can talk about what functionality it should have while looking at what is there already, so I made a draft pull request. Need to discuss: 
- necessary compatibility parameters
- further functionality
- how the history should be updated
