### ISSUE TITLE
Redundancy Code assumes Nblts = Nbls * Ntimes, 

### ISSUE THREAD

**Issue by mkolopanis** [RadioAstronomySoftwareGroup/pyuvdata#528]
Two issues really regarding the redundancy calculator:

The wrapper for utils.get_baseline_redundancies in a UVData object assumes 
- Nblts = Nbls*Ntimes This is not necessarily an assumption made by the uvdata class
- the `uvw_array` and `basline_array` are ordered such that baselines is the faster changing axis.  This may be an issue for most users, however it may not necessarily be true too.

See code:
https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/ebe8cfd567928eea9d2ae5b8c576f73b6372f206/pyuvdata/uvdata.py#L3250-L3253

**Comment by aelanman** [comment]
I suppose the way to fix this would be either to do a unique() selection on the uvw_array, or to use the resorting methods to ensure those conditions are met before doing the compression. The second option will only be possible once issue #427 is resolved.

Which solution is best depends on what `UVData.get_baseline_redundancies` is used for. If it's just being called by `compress_by_redundancy` then everything gets reordered anyway so we might as well sort it. If the blts axis needs to stay in the given order, then we can use np.unique to get the baseline vectors and indices.
