### ISSUE TITLE
read_uvh5 -- write_uvfits does not keep flags for H2C data

### ISSUE THREAD

**Issue by nkern** [RadioAstronomySoftwareGroup/pyuvdata#537]
@plaplant There seems to be a bug with reading `uvh5` files and then writing as `uvfits`, as none of the flags in the `uvh5` are propagated: more specifically, everything is flagged in the resultant `uvfits` files. Interestingly, this is only the case for `uvh5` files from H2C: I don't see this behavior from `uvh5` files from IDR2. My workflow is something like
```
uvd = UVData()
uvd.read_uvh5("h2c_xyz.uvh5")
# apply some flags
del uvd.extra_keywords['cminfo']
del uvd.extra_keywords['finfo']
uvd.write_uvfits("h2c_xyz.uvfits", force_phase=True, spoof_nonessential=True)
```
when upon reading the `uvfits` file, the `flag_array` is all True.

LMK if you have any ideas about this, thanks!

**Comment by nkern** [comment]
@plaplant helped me realize this is b/c the data has `nsamples` = 0 for all pixels. Manually setting `nsamples` to 1 fixes this problem.

**Comment by bhazelton** [comment]
@plaplant is this a known bug in the correlator?

**Comment by plaplant** [comment]
Yes, this is a known bug. It should be fixed in the near future.
