### ISSUE TITLE
update docstrings to put parameter and return types in the right place

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyuvdata#542]
To ensure that they're rendered properly in the docs.

example:
Args:
     param1 (int):
           description of parameter 1
     param2 (list(int)):
           description of parameter 2

**Comment by plaplant** [comment]
Much like there is pycodestyle, there is [pydocstyle](https://github.com/PyCQA/pydocstyle), which might help us out here. The default is to conform to [PEP257](https://www.python.org/dev/peps/pep-0257/), though numpy style is also an option. If we wanted to get super fancy, we could add it to travis like we do with pycodestyle right now.

I've also seen [flake8](http://flake8.pycqa.org/en/latest/) used by other projects as one-stop-shopping for code style, docstring style, and code complexity/correctness checking. Might be something to look into as well.

**Comment by bhazelton** [comment]
So what we're currently using is closest to google style (I think). I'd be happy to push towards including pycodestyle or flake8 (which I don't know much about) in our CI checks.

**Comment by mkolopanis** [comment]
a slightly related issue from the pydocstyle team: https://github.com/PyCQA/pydocstyle/issues/275
there _may_ be support for googledoc style, and pycodestyle cannot tell the difference between numpy style and googledoc style.

**Comment by bhazelton** [comment]
Discussed on telecon (3/15/19)
We should either go with Google or Numpy docstring style. There are slight preferences for numpy, but that will involve more changes. We did not come to a decision. If someone takes this on, they can have a majority vote.

**Comment by bhazelton** [comment]
When this issue is fully addressed, a `D` should be added to the flake8 `select` list in setup.cfg.

**Comment by bhazelton** [comment]
We have agreed to using numpy style, work is in process to fully comply. We have a checkbox on the PR template to remind us about this.

**Comment by steven-murray** [comment]
And since we're using flake now, we should use `flake8-docstrings`, and also `flake8-rst-docstrings` to ensure everything's OK.

**Comment by bhazelton** [comment]
yes, that's what I was alluding to above in adding `D` to the flake8 select list.
