### ISSUE TITLE
How to cite should be in the README

### ISSUE THREAD

**Issue by adampbeardsley** [RadioAstronomySoftwareGroup/pyuvdata#554]
We should include a link to the JOSS article.
http://joss.theoj.org/papers/10.21105/joss.00140

**Comment by dannyjacobs** [comment]
<img width="764" alt="Screenshot 2019-03-31 12 56 18" src="https://user-images.githubusercontent.com/63191/55294247-6843c000-53b4-11e9-81f9-e48567f9e23e.png">
second :/
