### ISSUE TITLE
Add item to readme about telescopes we've used pyuvdata on

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyuvdata#577]
Also track (internally) people who have used it on each telescope.

Maybe also add tag to PRs/Issues related to the telescopes.

**Comment by bhazelton** [comment]
MWA, HERA, PAPER, LWA, ALMA, VLA?

**Comment by jpober** [comment]
Somehow instruct new users to add telescopes to this list if they wind up using pyuvdata on something we've never used before
