### ISSUE TITLE
Inflate by redundancy mapping

### ISSUE THREAD

**Issue by aelanman** [RadioAstronomySoftwareGroup/pyuvdata#586]
https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/a858a6c6663153345bbfecaa203f369ccda97647/pyuvdata/uvdata.py#L3825-L3826

It is not generally true that `Nblts == Nbls * Ntimes`. Currently `UVData.inflate_by_redundancy` makes this assumption when building the map from compressed to inflated data arrays.

To fix this we need to know which redundant groups have data available at each time. This may require for loops and other ugliness.

**Comment by mkolopanis** [comment]
if we know the number of times for each type of baselines [numpy repeat](https://docs.scipy.org/doc/numpy/reference/generated/numpy.repeat.html) can be a useful friend.
