### ISSUE TITLE
Make sure find redundancy methods only put each baseline in one redundant group

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyuvdata#615]
Should be asserts to enforce that if it's already the case.

**Comment by aelanman** [comment]
It is technically possible for baselines to be in multiple redundant groups if the redundancy tolerance is large enough. Should this be an error if trying to use inflate/compress methods?

**Comment by bhazelton** [comment]
I think so. It came up in the discussion around the last PR and I forgot to get it resolved before merging. I guess one option is to force baselines into whichever group they're closest to. We should probably talk about this more to come up with the best solution.

**Comment by aelanman** [comment]
My thinking right now is that when compressing by redundancies, you're assuming that measurements are identical among redundant baselines. We can't make that assumption if there are partial overlaps between redundant groups, which will only happen if the position tolerance is too high.

**Comment by bhazelton** [comment]
From telecon: Should be an error inflate & compress, warning for methods that construct redundant sets.

**Comment by bhazelton** [comment]
@aelanman can you take a look at this?
