### ISSUE TITLE
Intersecting selections

### ISSUE THREAD

**Issue by aelanman** [RadioAstronomySoftwareGroup/pyuvdata#616]
UVData.select() does not behave as expected when run with both `bls` and `antenna_nums`.  This may be a broader issue with using multiple selection keywords. In the following example, the expectation is that it will select only baselines that meet both criteria:

```
# coding: utf-8

from pyuvdata import UVData
import numpy as np

uv = UVData()
uv.antenna_numbers = np.arange(10)
uv.antenna_names = np.arange(10).astype(str)
uv.ant_1_array, uv.ant_2_array =  map(lambda x: x.flatten(), np.meshgrid(np.arange(10), np.arange(10)))
uv.baseline_array = uv.antnums_to_baseline(uv.ant_1_array, uv.ant_2_array)

uv.Nblts = uv.ant_1_array.size
uv.Nants_data = uv.Nants_telescope = 10
uv.Nbls = uv.ant_1_array.size
uv.Ntimes = 1
uv.time_array = np.arange(uv.Nblts)
uv.lst_array = np.arange(uv.Nblts)
uv.integration_time = np.array([1] * uv.Nblts)
uv.uvw_array = np.zeros((uv.Nbls, 3))
uv.history = ''
uv.select(bls=[(0,1), (1,2), (0,3)], antenna_nums=[1,2,3], metadata_only=True)

assert uv.Nbls == 1
```
The expectation is for the intersection of these sets, `[(1,2)]`.
Instead, the selected baselines are:
```
[(0, 1), (0, 3), (1, 1), (1, 2), (1, 3), (2, 1), (2, 2), (2, 3), (3, 1), (3, 2), (3, 3)]
```

This is the union of the `bls` and `antenna_nums` selections.

**Comment by bhazelton** [comment]
I think we need to discuss whether `select` should use intersections or unions when there are multiple selections along the blt axis. Currently different combinations use union and intersection, so they are inconsistent.

**Comment by bhazelton** [comment]
From telecon: everything should be an intersection.
