### ISSUE TITLE
baselines_to_antums is not vectorized

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvdata#619]
Seems you can't give a list of baseline numbers and get a list of antenna pair tuples.  That would be useful.

**Comment by mkolopanis** [comment]
you are able to provide a numpy array to `baseline_to_antnums` and the returned value will be a tuple (ant_1_array, ant_2_array). This is used in the `uvh5.py` module, changing the functionality to return a list of antenna pairs could break other code, though that could be changed if necessary. It is easy enough to accept a list as an entry to this function though and still have the output be (ant_1_array, ant_2_array)

**Comment by jpober** [comment]
Oh, good.  We must have been trying a list.  Some documentation to that effect should close the issue.
