### ISSUE TITLE
add uvd.select(times=[time_min, time_max]

### ISSUE THREAD

**Issue by jaguirre** [RadioAstronomySoftwareGroup/pyuvdata#627]
Add a select function that allows a time range rather than explicit time samples.  This should make it much easier to do the select once we have BDA (which will have different time samples for different baseline lengths).  Potentially it could also speed the selection by not requiring explicit matching of every time in the list, but just time_min <= t < time_max.

**Comment by bhazelton** [comment]
This should be implemented as a `time_range` keyword, not by overloading the `times` keyword.
