### ISSUE TITLE
iterator for "data-like" attributes

### ISSUE THREAD

**Issue by steven-murray** [RadioAstronomySoftwareGroup/pyuvdata#637]
It would be good to have some kind of iterator over the "data-like" attributes of the `UVData` class, which would then also lend itself to quickly determining whether the current instance was a "metadata-only" object.

**Comment by jpober** [comment]
Alternatively (additionally?), we could just have a parameter on UVData that identifies the object as metadata only and then relevant methods check for this parameter and behave differently.
