### ISSUE TITLE
Antenna positions

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvdata#65]
antenna_positions is currently not required, but we now have the code to generate it from uvws.  We should make it required, try reading it from the file, and calculate it if necessary.  We will probably also want to add a check that the ones read from the file match closely with those calculated from the uvws, as some files (ahem PAPER correlator) write incorrect things into the antenna table.

**Comment by bhazelton** [comment]
One block on this was FHD not reading/writing antenna positions (issue #34) that has been fixed on the FHD side, once we address that issue on the pyuvdata side we will be closer to requiring antenna positions.

**Comment by bhazelton** [comment]
Ok, support for objects with no antenna positions has been marked as deprecation pending. I'm not quite sure we have the code to get antenna positions from UVWs, only the other way around, but we do now have the code to get antenna positions from FHD.

Unless we come up with a way to get antenna positions from the uvws, I think we've done what we can for now (absolutely requiring them needs to wait for a future version).

**Comment by aelanman** [comment]
How do we generate antenna positions from uvw? I was under the impression that that you need at least one known absolute antenna position to do that, unless we're defining a particular antenna to be at the `telescope_location`.

**Comment by bhazelton** [comment]
Yeah, I'm not at all sure how to do that, but the issue references some such code.

**Comment by bhazelton** [comment]
I'm going to close this issue since the deprecation process has been started. I'll open another issue to track actually deprecating.
