### ISSUE TITLE
Should UVData.read take arrays of filenames?

### ISSUE THREAD

**Issue by adampbeardsley** [RadioAstronomySoftwareGroup/pyuvdata#654]
@kbharatgehlot was trying to read a set of files, and happened to have them in a numpy array (output of np.sort). I don't see a reason we shouldn't support that as an input to read.

**Comment by bhazelton** [comment]
I agree, I think arrays and lists should be handled the same.

**Comment by bhazelton** [comment]
May need to be fixed in UVCal and UVBeam as well.
