### ISSUE TITLE
make an `extras_require` section setup.py

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyuvdata#675]
To have a place to put all the optional dependencies so that people can install if needed.

**Comment by steven-murray** [comment]
What are the current optional dependencies? It may make sense to have more than one key in there: maybe a `dev` and `all` or something.

**Comment by bhazelton** [comment]
I think we may need several keys. The optional dependencies are listed in the readme:
* h5py (for reading and writing uvh5 format and uvflag save files)
* python-casacore (for working with CASA measurement sets)
* healpy (for working with beams in HEALPix formats)
* pyyaml (for working with settings files for CST beam files)

**Comment by steven-murray** [comment]
I'm not sure what the guidelines are for adding keys that add a single package -- obviously that can be achieved by just also installing the extra package. Could we do something like

```
extras_require = {
    'h5': ['h5py'],
    'casa': ['python-casacore'],
    'healpix': ['healpy'],
    'cst': ['pyyaml'],
    'formats': ['h5py', 'python-casacore', 'healpy', 'pyyaml'],
    'dev': [<all of the above>, 'sphinx', 'pytest', ...]
}
```

**Comment by bhazelton** [comment]
That seems reasonable but I should probably go read a little about `extras_require`.
