### ISSUE TITLE
Define criteria for RASG core and RASG affiliated repos

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyuvdata#686]
Idea is to split these into 2 different Github organizations to make it more clear which is which.
Need to have clear criteria and guidelines for deciding where projects belong.

**Comment by bhazelton** [comment]
we now have a rasg-affiliates org.

Need criteria for each org.

Goal is to help open source radio astronomy software that is broadly useful to the community to adopt high software development and community standards. We want to encourage software to be community developed and supported, stable, well-maintained and well documented.

Our core software repositories are hosted in the primary RASG git organization. Repositories that are adopting RASG standards and moving towards our goals are hosted in our rasg-affiliates git organization.

rasg-affiliates:
- continuous integration set up to run tests & report coverage with badges on readme
- pip installable from the repo
- A descriptive readme
- Code documentation, including but not limited to docstrings (we prefer numpy docstring style).
- Meet pep8 code format standards (flake8 or pycodestyle can be used to enforce this).
- permissive open source license (e.g BSD or MIT, NOT a copyleft license)
- signoff from the RASG managers (will consider community usefulness and plan for long-term support)

rasg core repos:
- Partnership with multiple RASG core developers and/or managers who commit to developing and maintaining the repo over the long term.
- Deep community support and development. It is often easiest to achieve this by developing code as a community from the beginning, but it can be met with revision based on deep community input.
- Better than 95% code coverage.
- Meet all the criteria for rasg-affiliates.

**Comment by adampbeardsley** [comment]
Did we ever settle on whether there is a path to "graduation?" Either way, needs to be clearly documented somewhere.

**Comment by bhazelton** [comment]
This was done on the github.io repo in mid Feb.
