### ISSUE TITLE
Reorganize directory structure

### ISSUE THREAD

**Issue by mkolopanis** [RadioAstronomySoftwareGroup/pyuvdata#696]
Should the directory structure be reorganized such that files associated with a give object are arranged in subdirectory? e.g. all UVData and associated reading subclasses are put into a UVData folder, all UVBeam related files in a Beam subdirectory

**Comment by steven-murray** [comment]
I think it's a good idea, but I think it would have to be on a major version release -- it is possible that it will break current user's code (although easy to fix).

**Comment by mkolopanis** [comment]
Would it really? I would not have thought it would.

**Comment by steven-murray** [comment]
If a user has `UVData` imported directly as `from pyuvdata.uvdata import UVData`, then unless you exactly replicate this module path then their import will break. Most users will just be doing `from pyuvdata import UVData`, which should be easy to keep by managing the `__init__.py`.

**Comment by mkolopanis** [comment]
Ah that makes a lot of sense!

**Comment by bhazelton** [comment]
Let's do it as part of version 1.5, I don't expect it will break things for most users (do it right before the new version).

**Comment by bhazelton** [comment]
One option would be to leave the files (basically have them import from the new location) and have them issue a deprecation warning.

**Comment by mkolopanis** [comment]
I have started working on this, however have a bit of a concern. We want to issue a warning if someone tries `from pyvdata.uvdata import UVData` which means we still need a `uvdata.py` in the top level of the directory. The concern I have is what to name the directories for each type of object. Should all uvdata related modules go in a folder name UVDATA? We can't use lower cased `uvdata` because that would overload (and probably take precedence over) the module that is issuing a warning.

We could always rename directories after we drop the warning import modules too. because that should be obscured from the user

**Comment by bhazelton** [comment]
Since we agreed we're doing this in version 2.0, I'm more ok with just making it a breaking change. What do you think @plaplant @steven-murray ?

**Comment by mkolopanis** [comment]
so we'll just bump to 2.0 as soon as I'm done here :P

**Comment by bhazelton** [comment]
Hmm. Maybe we need a 2.0 branch that this and other major changes are merged into? Not sure what the best way is.

**Comment by mkolopanis** [comment]
Sounds like it could be a disaster to rebase once other big 1.0 things happen though. Maybe we should start a 2.0 milestone to identify what it will take to push us to 2.0?

**Comment by mkolopanis** [comment]
honestly the directory structure stuff is easy, I wouldn't worry about re-creating it later down the line.

**Comment by bhazelton** [comment]
we have a milestone!

**Comment by mkolopanis** [comment]
peaking at how astropy does it, they seem to like to branch a lot, maybe that's not a bad idea. oh i must have missed that milestone
