### ISSUE TITLE
unphase_to_drift gives SkyCoord attribute error

### ISSUE THREAD

**Issue by PyxieLouStar** [RadioAstronomySoftwareGroup/pyuvdata#711]
I'm using `uv.unphase_to_drift()` after `uv.phase(ra, dec)`. This is generating the following error:
```
line 769, in unphase_to_drift
    frame_uvw_coord = SkyCoord(x=uvw_rel_positions[:, 0] * units.m + frame_telescope_location.x,

  File "/Applications/anaconda/lib/python3.5/site-packages/astropy/coordinates/sky_coordinate.py", line 521, in __getattr__
    .format(self.__class__.__name__, attr))

AttributeError: 'SkyCoord' object has no attribute 'x'
```

**Comment by bhazelton** [comment]
@PyxieLouStar can you provide a minimum working example and details of your operating system and versions of pyuvdata and astropy? I'm not seeing this in the little bit of testing I've done.

**Comment by PyxieLouStar** [comment]
Running my code again I no longer get the error. Yay! I'm currently using pyuvdata version 1.5.0 and astropy version 3.0.4.
