### ISSUE TITLE
astropy-healpix dep

### ISSUE THREAD

**Issue by steven-murray** [RadioAstronomySoftwareGroup/pyuvdata#717]
It seems like when installing `pyuvdata` with pip, `astropy-healpix` needs to be installed manually (at least, in `hera_sim` we need to, for tests). This should be fixed.

**Comment by bhazelton** [comment]
related to #675 I think.

**Comment by mkolopanis** [comment]
yeah I think so too, `astropy-healpix` is not listed in the `setup.py` at all so it makes sense that it is not being grabbed by `pip`

**Comment by bhazelton** [comment]
to be clear: astropy-healpix is not required to run many parts of pyuvdata or to run pyuvdata tests. It is required if you want to use healpix in beams.
