### ISSUE TITLE
polarization select on read

### ISSUE THREAD

**Issue by mwilensky768** [RadioAstronomySoftwareGroup/pyuvdata#731]
On two different machines, with two different versions of pyuvdata:

(1) Mac OSX 10.11.6, pyuvdata version 1.4.0
(2) Max OSX 10.15.1, pyuvdata version 1.4.2

Trying to use the `polarizations` keyword when calling the generic `read` method from within a jupyter notebook is resulting in either an infinite loop or some other behavior that results in the cell never finishing. Using select on read for other keywords, such as `times` and `ant_str` is fine, and using `polarizations` _after_ reading in the data is fine.

**Comment by bhazelton** [comment]
@mwilensky768 this is specifically for uvfits, right? Can you paste in the calls you did?

**Comment by mwilensky768** [comment]
```
from pyuvdata import UVData

infile = '/Volumes/Faramir/uvfits/1061312032.uvfits
UV = UVData()
UV.read(infile, read_data=False)
times = np.unique(UV.time_array)[3:-3]
polarizations = UV.polarization_array[0]
UV.read(infile, times=times, polarizations=polarizations)
```

I have not tested this on other file types.

**Comment by mwilensky768** [comment]
It looks like this did not happen on a uvh5 file that I used.

**Comment by mkolopanis** [comment]
Seems like we have thrown this to the wayside. What are our action items here? Should we try to duplicate this on other platforms? Do we need a pow-wow?

**Comment by mwilensky768** [comment]
I can try to duplicate it on the machine it was happening on. I will say it was on a super old version of mac os so it may is probably pointless to fix.

**Comment by mwilensky768** [comment]
OK, after having updated that machine in various ways, the problem seemed to have disappeared.

**Comment by bhazelton** [comment]
I'm inclined to close this issue in that case, but it can be re-opened if anyone experiences something similar.
