### ISSUE TITLE
Add telescope location information to UVCal

### ISSUE THREAD

**Issue by dstorer** [RadioAstronomySoftwareGroup/pyuvdata#735]
Right now, when looking at calibration solutions, I need to also read in a uvdata object just to get the telescope location so I can convert the times to LST. It would make things more efficient to only need to read in uvcal objects.

**Comment by bhazelton** [comment]
should maybe be added as part of addressing #753

**Comment by bhazelton** [comment]
maybe also add an lst_array.

**Comment by theo-kunicki** [comment]
We should also probably include antenna positions in the object.
