### ISSUE TITLE
Unable to load CASA measurement sets for both simulated data and observed data

### ISSUE THREAD

**Issue by Arnabiitindore** [RadioAstronomySoftwareGroup/pyuvdata#736]
Hi, 
I am unable to load the CASA ms files in pyuvdata. I have installed the latest version of pyuvdata also astropy and numpy and casacore are latest version installed using conda. 
Everytime, I am trying to load the data one error is showing - 

/home/arnab/anaconda2/lib/python2.7/site-packages/astropy/utils/iers/iers.pyc in _check_interpolate_indices(self, indices_orig, indices_clipped, max_input_mjd)
    272         """
    273         if np.any(indices_orig != indices_clipped):
--> 274             raise IERSRangeError('(some) times are outside of range covered '
    275                                  'by IERS table.')
    276 

IERSRangeError: (some) times are outside of range covered by IERS table.

I have tried for both GMRT observation also simulation of HERA,MWA,SKA using CASAsim. 

However, it worked perfectly when I simulate HERA using PRIsim using Nithyanandan Thyagarajan's simulation tool . 

I do not know what's wrong in CASA ms set.

**Comment by bhazelton** [comment]
I believe this is related to some problems with the USNO IERS servers, which was accounted for in astropy 3.2.3. Can you check what version of astropy you have installed?

**Comment by Arnabiitindore** [comment]
Yes. It seems version problem of astropy.  I have installed now astropy4.0. and it works. Here is the output of the iptyhon attached : 

In [1]: import astropy                                                                                                                         

In [2]: from pyuvdata import *                                                                                                                 

In [3]: uv = UVData()                                                                                                                          

In [4]: uv.read_uvfits('sem_trecs_mwa_old_64chan_z_9_125KHz_resolution_8MHz_BW.fits')                                                          
Telescope VLA is not in known_telescopes.
Downloading ftp://cddis.gsfc.nasa.gov/pub/products/iers/finals2000A.all from https://datacenter.iers.org/data/9/finals2000A.all
|=========================================================================================================| 3.3M/3.3M (100.00%)         1s

In [5]: astropy.__version__                                                                                                                    
Out[5]: '4.0'
