### ISSUE TITLE
Unable to load miriad uv data

### ISSUE THREAD

**Issue by bjnorfolk** [RadioAstronomySoftwareGroup/pyuvdata#737]
Hi,

I'm attempting to read in miriad uvfits files from ATCA observations. I'm following the tutorial in the docs:
```python
from pyuvdata import UVData
>>> UV = UVData()

# This miriad file is known to be a drift scan.
# Use either the file type specific read_miriad or the generic read function,
# optionally specify the file type
>>> miriad_file = 'hd97048.34000.uvavg'
>>> UV.read_miriad(miriad_file)
>>> UV.read(miriad_file, file_type='miriad')
>>> UV.read(miriad_file)
```

I get the error

```
"Altitude is not present in Miriad file, and telescope ATCA is not in known_telescopes. Telescope location will be set using antenna positions.
Telescope location is set at sealevel at the file lat/lon coordinates. 
Antenna positions are present, but the mean antenna position does not give a telescope_location on the surface of the earth. 
Antenna positions do not appear to be on the surface of the earth and will be treated as relative."`
```
```python
RuntimeError: dictionary changed size during iteration
```

Any tips?
Thanks,

**Comment by bhazelton** [comment]
@bjnorfolk sorry for the delay. I think the messages about altitude and telescope location are just warnings, probably not the cause of the runtime error. Can you point me to where I can download a sample file that causes this error so I can debug it?

**Comment by bjnorfolk** [comment]
Hi @bhazelton,
Thanks for the reply, sorry for my delay I've been on holidays.

Here's the uv data I'm attempting to load with UVData [https://drive.google.com/file/d/1i3oTggrnJ933DRCK1a0v5TzkR4TikbsC/view?usp=sharing](url)

Let me know if you have any issues downloading it.

Thanks,

**Comment by bhazelton** [comment]
@bjnorfolk I'm not getting a RunTime error on my machine, can you give me some details about your system, including what version of python you're running, and what operating system you're running on?

**Comment by bjnorfolk** [comment]
I'm using Python 3.7.1 on Mojave 10.16.4, was there anything else you needed?

**Comment by bjnorfolk** [comment]
Here's a screenshot of the run time error in case I missed any information 
![image](https://user-images.githubusercontent.com/34231154/71855584-915c6280-3135-11ea-9906-41643038cb86.png)

**Comment by bhazelton** [comment]
Thank you, that's helpful. I just tried it with python 3.7 on Catalina and still don't get the error, but that screenshot gives me enough information to go digging in the code to see if I can see something that might be causing a problem.

**Comment by bjnorfolk** [comment]
@bhazelton I've successfully read the miriad file. I decided to create a new conda environment given your success, with just conda installing pyuvdata and ipython. However, I receive a new error when writing to uvfits.
I receive the comment
```python
refpnt in extra_keywords is a list, array or dict, which will raise an error when writing uvfits or miriad file types
```
after I read the file and consequentially, receive the type error after attempting to write: ```python
TypeError: Extra keyword refpnt is of <class 'numpy.ndarray'>. Only strings and numbers are supported in uvfits.`
```
Here's the terminal read out. 
![image](https://user-images.githubusercontent.com/34231154/71942075-20d64400-3210-11ea-9b7d-54fef033aa63.png)

**Comment by bhazelton** [comment]
@bjnorfolk Interesting! It looks like there's a variable `'refpnt'` that is an array that pyuvdata doesn't know how to put into the uvfits file. We store these kinds of variables that are unknown to pyuvdata but that someone might not want to loose in the `extra_keywords` dictionary on the object. The quick thing to do is to just remove it from that dictionary (`del UV.extra_keywords['refpnt']`.

If that variable is important and needs to be preserved between files we can do some more work to better integrate it with the object, but I don't see it in the Miriad documentation I have, so I don't know what it is.

**Comment by bjnorfolk** [comment]
Currently I don't think I need the variable, thanks for the help!
