### ISSUE TITLE
Make all names pythonic

### ISSUE THREAD

**Issue by steven-murray** [RadioAstronomySoftwareGroup/pyuvdata#745]
It would be nice to have all function and variable names in `snake_case`, and class names in `CamelCase`. 

One example is `uvtest.checkWarnings`, which is a function.

There's a `flake8` plugin called `pep8-naming` which can enforce this for us as well.

**Comment by bhazelton** [comment]
We are agreed that we are not going to change the `N*` parameters (e.g. Nfreqs, Ntimes).

**Comment by bhazelton** [comment]
the checkWarnings name change is being tracked in #836, the other ones (N* names) we aren't going to change.
