### ISSUE TITLE
Add list of methods to the top of object doc pages

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyuvdata#751]
It would be nice to have a list of the methods on our primary user classes at the top of the doc pages with links to the detailed docstrings for each one. Something similar for the utility functions would be good too.

**Comment by bhazelton** [comment]
This might be the right place to start: https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html

**Comment by steven-murray** [comment]
I've used autosummary a bit. It's nice, but it can be a little finnicky, depending on how the code is laid out. I can see if I can help with this in ~2 weeks or so.

**Comment by bhazelton** [comment]
There's been some significant improvements to the docs structure since I made this, I think it's good enough now.
