### ISSUE TITLE
pull uvbase & parameter objects out of pyuvdata into their own repo.

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyuvdata#762]
So we don't have to depend on pyuvdata.

**Comment by mkolopanis** [comment]
To be explicit, so [`pyradiosky`](https://github.com/RadioAstronomySoftwareGroup/pyradiosky) does not need to depend on pyuvdata.

**Comment by bhazelton** [comment]
We talked about this on the pyuvdata telecon. Paul was opposed to this, he'd prefer not to introduce another pyuvdata dependency and complicate the build environment for pyuvdata users.

**Comment by bhazelton** [comment]
Current plan is to have pyradiosky depend on pyuvdata for the UVBase and UVParameter objects.
