### ISSUE TITLE
No choice of conjugation convention for gains 

### ISSUE THREAD

**Issue by mkolopanis** [RadioAstronomySoftwareGroup/pyuvdata#764]
The "multiply" and "divide" convention can be specified on a UVCal object, but the user has no control over conjugation convention of gains when being applied to data. It does not seem impossible that a telescope could choose to conjugate gain 1 opposed to gain 2 which is done by default in `utils.uvcalibrate`.

I suppose you could get around this by conjugating all the gains before applying, but that seems silly.

**Comment by bhazelton** [comment]
We need to specify a convention in the UVCal object that specifies that calibration solutions follow a specific convention about which antenna in the pair is conjugated.

**Comment by bhazelton** [comment]
Need to talk to current UVCal users to try to break as few things as possible.

**Comment by bhazelton** [comment]
Given that this is a convention about how the visibilities are formed, maybe this should be a parameter on UVData rather than UVCal. It should also be a keyword to the `uvcalibrate` function, so that it can be overridden or set by the user.

**Comment by bhazelton** [comment]
We don't really understand the mechanism by which various conventions are selected in calibration algorithms. So the easiest thing might just be to add an option to `uvcalibrate` to allow the user to swap the gain convention if they need to.
