### ISSUE TITLE
Use pytest.warns to check warning messages rather than our own checkWarnings function

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyuvdata#766]
This would naturally also take care of the example called out in #745.

See: https://docs.pytest.org/en/latest/warnings.html#warns

**Comment by mkolopanis** [comment]
I think there's a lot of good built in features out in house CheckWarning has that are possible to do with pytest.warns but would have to be done manually. For instance checking the number of warnings, and each message separately for multi-warning scenarios. We might consider just having the in house function wrap pytest.warns?
