### ISSUE TITLE
One corrupted file breaks entire read

### ISSUE THREAD

**Issue by dstorer** [RadioAstronomySoftwareGroup/pyuvdata#783]
When reading in a whole list of files (specifically I've been using read_uvh5), if any one of the files is corrupted the entire read breaks. I propose adding an optional (defaulted off) try-catch block to catch potentially problematic files so that the rest of the read may continue. I think it would also make sense to print out a list of any files that had to be skipped. 

I will draft a PR that does this.

**Comment by bhazelton** [comment]
was fixed in 788
