### ISSUE TITLE
set_phase breaks phase_to_time?

### ISSUE THREAD

**Issue by anguta** [RadioAstronomySoftwareGroup/pyuvdata#806]
I am using `pyuvdata=2.0.1`, `numpy=1.18.1` and `astropy=4.0.1.pos1`

Here, I try to phase the data in an observation. 

``` 
uvd = UVData()
uvd.read('zen.2458792.52644.sum.uvh5')
uvd.set_phased()
uvd.phase_to_time(Time(np.mean(uvd.time_array),format='jd'))
```

And I receive the following error. 

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-51a5087ca28b> in <module>
     15 uvd.read('zen.2458792.52644.sum.uvh5')
     16 uvd.set_phased()
---> 17 uvd.phase_to_time(Time(np.mean(uvd.time_array),format='jd'))
     18 
     19 hc7 = HERACal('zen.2458792.52644.sum.abs_master_flag7.calfits')

/lustre/aoc/projects/hera/aewallwi/env/envs/hera3dev/lib/python3.7/site-packages/pyuvdata/uvdata/uvdata.py in phase_to_time(self, time, phase_frame, use_ant_pos, allow_rephase, orig_phase_frame)
   2481             use_ant_pos=use_ant_pos,
   2482             allow_rephase=allow_rephase,
-> 2483             orig_phase_frame=orig_phase_frame,
   2484         )
   2485 

/lustre/aoc/projects/hera/aewallwi/env/envs/hera3dev/lib/python3.7/site-packages/pyuvdata/uvdata/uvdata.py in phase(self, ra, dec, epoch, phase_frame, use_ant_pos, allow_rephase, orig_phase_frame)
   2260                     ra,
   2261                     rtol=self._phase_center_ra.tols[0],
-> 2262                     atol=self._phase_center_ra.tols[1],
   2263                 ) or not np.isclose(
   2264                     self.phase_center_dec,

<__array_function__ internals> in isclose(*args, **kwargs)

TypeError: no implementation found for 'numpy.isclose' on types that implement __array_function__: [<class 'astropy.coordinates.angles.Longitude'>]
```

It looks like `pyuvdata` is trying to call `numpy.isclose` on an `astropy.coordinates.angles.Longitude object`.  Should we instead be calling `isclose` on `ra.deg` ?

**Comment by anguta** [comment]
digging into this more, I am finding some puzzling behavior.  

First of all, there are some wierd things going on in the following code-block (lines 2258-2271
```
                if not np.isclose(
                    self.phase_center_ra,
                    ra,
                    rtol=self._phase_center_ra.tols[0],
                    atol=self._phase_center_ra.tols[1],
                ) or not np.isclose(
                    self.phase_center_dec,
                    dec,
                    rtol=self._phase_center_dec.tols[0],
                    atol=self._phase_center_dec.tols[1],
                ):
                    self.unphase_to_drift(
                        phase_frame=orig_phase_frame, use_ant_pos=use_ant_pos
                    )
```
beyond `ra` and `dec` being `astropy.coordinates.angles` objects, `self.phase_center_ra` and `self.phase_center_dec` are `None` while `self._phase_center_ra` and `self._phase_center_dec` are properly set to `astropy.coordinates.angles` obejcts. So the `isclose` will also fail once we change `ra` to `ra.deg` because `self.phase_center_ra=None`.

**Comment by anguta** [comment]
The problem seems to go away when I don't call `hd.set_phased()`.

**Comment by plaplant** [comment]
@anguta raw HERA data is unphased, so it shouldn't have an existing phase center. What happens when you call `phase_to_time` without calling `set_phased()` first?

**Comment by anguta** [comment]
Things seem to work when I don't call `set_phased()`.

**Comment by plaplant** [comment]
Okay, glad it's working. Closing this since it seems to be fixed. Feel free to reopen if need be.

**Comment by anguta** [comment]
Is it a usability concern that calling `set_phased()` seems to eliminate ones ability to set a phase center afterwards?

**Comment by plaplant** [comment]
I don't think `set_phased()` is typically called by the user directly. It's generally called by the phasing methods to indicate a drift dataset has been phased and requires phasing-specific metadata, or by UVData file-specific subclasses when reading phasing information from files, as here:

https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/c61ffa8741bdd7fd9198e42163b7774778c72570/pyuvdata/uvdata/uvh5.py#L221-L235

We should probably adjust the docstring of the function to make it clear that that function generally shouldn't be called by the user, or maybe make it a private method. I will make a separate issue for that. Thanks for pointing this out!

**Comment by plaplant** [comment]
Also note there is a brief section in the tutorial about how to do phasing: https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/docs/tutorial.rst#uvdata-phasing
