### ISSUE TITLE
Improve documentation of set_phased and other UVData methods and make them private

### ISSUE THREAD

**Issue by plaplant** [RadioAstronomySoftwareGroup/pyuvdata#807]
As discussed in #806, there may be an ambiguity to users about how methods like `set_phased` or `set_drift` should be used (or not used, as it were). I think that users generally shouldn't call these directly, but that's not clear from the docstrings as currently written. We should improve the docstrings to explain their intended use more clearly. We could also consider making these methods private, but that would require deprecation warnings to handle the API change and may not actually be necessary.

**Comment by bhazelton** [comment]
I think we should absolutely make these private, they are not intended to be called by users at all. I think it's worth the deprecation effort. That's in addition to fixing the docstrings.

**Comment by plaplant** [comment]
Okay sounds good. I'm on board with deprecating.
