### ISSUE TITLE
Telescope locations don't quite match for HERA

### ISSUE THREAD

**Issue by jsdillon** [RadioAstronomySoftwareGroup/pyuvdata#816]
```
import pyuvdata
pyuvdata.telescopes.get_telescope('HERA').telescope_location
```

gives me

`array([ 5109342.760375425 ,  2005241.90402741  , -3239939.4692640286])`

while

```
uvd = UVData()
uvd.read('2458838/zen.2458838.25535.sum.uvh5')
print(uvd.telescope_location)
```

gives me

`[ 5109325.85521063  2005235.09142983 -3239928.42475396]`

Is this a problem? Do we care?

**Comment by bhazelton** [comment]
I think this means that what we have in the pyuvdata repo doesn't quite match the COFA for HERA. I think this might be because it moved from the old PAPER center and hasn't been updated. I'll get the right values from Dave and update them in pyuvdata.

**Comment by jsdillon** [comment]
Here's the full precision numbers I pulled out of a H1C data files (and confirmed that H3C matches): 

https://github.com/HERA-Team/hera_cal/blob/1189e06f044c8416e327b2541919cc2edf1b3896/hera_cal/utils.py#L27-L29

**Comment by bhazelton** [comment]
Ok, I have a draft PR for this, but it requires some test files added in another PR so it can't be merged until that PR is.
