### ISSUE TITLE
Support writing auto- and cross-spectra separately in uvh5 files

### ISSUE THREAD

**Issue by plaplant** [RadioAstronomySoftwareGroup/pyuvdata#824]
There have been several instances where users have wanted to look at just auto-correlations from HERA data files. Currently these are being written interspersed with the cross-correlations, and the order in which they are written makes accessing them quite slow. One proposed solution is to write the auto-correlations and cross-correlations to different HDF5 datagroups inside of uvh5 files. This approach would allow for fast access of just auto-correlations, and should be relatively transparent to the user when doing partial I/O.

We'll want to build in backwards compatibility for files that use the current approach of having autos and crosses written together, while supporting these new-style files. The actual implementation may also require additional keywords in the header of uvh5 files. Any significant changes will be noted in the uvh5 memo defining the filetype spec.

**Comment by nkern** [comment]
@plaplant I think the easiest way to do this and maintain backwards compatability is to stack the autocorrelations first in the data_array, and then concatenate the crosses ordered per usual along the `Nblts` axis, and set an HDF5 chunk to `(Ntimes, 1, Nfreqs, 1)`. That chunk size may be too small for optimality, in which case something like `(Ntimes, 1, Nfreqs, Npols)` etc. could also work. If possible, chunking 1 across polarizations is nice for people who want to extract only a single pol from the files.

**Comment by plaplant** [comment]
@nkern that's definitely a possibility, and one worth exploring if it means that we don't have to develop a new format. My worry is that it might not be efficient enough, even with the new fast reading you've developed. We should do some profiling in the next few months to decide what's best.

I agree that we should set our chunk size to be something that's best for what most users/analysis codes want. We can include chunk size testing as part of our profiling.

**Comment by bhazelton** [comment]
This can be fixed by just putting all the autos contiguous (e.g. first in the file), we don't need extra data sets. Easiest path here is probably adding an option to `order` keyword of the `reorder_blts` method to sort autos first. Proposal is to add `'autos'` as a valid string to pass to that keyword to sort autos first.
