### ISSUE TITLE
mwa_corr_fits does not support metadata only reads

### ISSUE THREAD

**Issue by mwilensky768** [RadioAstronomySoftwareGroup/pyuvdata#830]
Using `/usr/bin/time -v` I've found that attempting a metadata-only read for 10G worth of MWA corr fits files takes about 50G of RAM. This seems unnecessary. It also appears that `UVData.read_mwa_corr_fits` does not have a `read_data` keyword, which may be the culprit i.e. the metadata-only functionality is not there to begin with.

**Comment by mkolopanis** [comment]
is the 50GB usage consistent with reading the whole file?

**Comment by bhazelton** [comment]
Oh, yeah, reading only the metadata isn't an option (yet) for mwa_corr_fits files, so that keyword is just being ignored.

**Comment by mkolopanis** [comment]
There are some other keywords like the check related that do not get set. Maybe I should add this stuff in as part of the #825 ?

**Comment by mwilensky768** [comment]
@mkolopanis the data array is indeed actually read in (because read_data=False is ignored). I'm going to assume that an ignored keyword isn't changing memory consumption and this this is consistent with reading the whole file in with read_data=True.

**Comment by mwilensky768** [comment]
Just for the record, it seems reading in a similar-sized uvfits file metadata-only style does not have memory issues, so I think this is strictly caused by not actually doing metadata-only. I will change the title of the issue.
