### ISSUE TITLE
bls default is empty list in UVData._select_preprocess

### ISSUE THREAD

**Issue by mwilensky768** [RadioAstronomySoftwareGroup/pyuvdata#835]
The keyword `bls` is default set to `[]` in `UVData._select_preprocess`. I have run into problems with this in SSINS due to how python handles default keyword settings of this form. See this page:

https://docs.python-guide.org/writing/gotchas/

Unsure if intentional.

**Comment by mkolopanis** [comment]
can you link to this in the code? I do not see this happening even searching through it.

**Comment by mwilensky768** [comment]
Uh, sorry. I think I read a pytest error log incorrectly. I'll close this.
