### ISSUE TITLE
Use of mutable defaults in checkWarnings.

### ISSUE THREAD

**Issue by mkolopanis** [RadioAstronomySoftwareGroup/pyuvdata#836]
#835 got me hunting and I did find a spot with poor choice of defaults. The list and dict defaults used in the checkWarnings call could cause issues with repeated calls.

https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/4c1c67efe488e8ea77bc2755ae68357aecad7920/pyuvdata/tests/__init__.py#L33-L41

**Comment by bhazelton** [comment]
yeah, if we keep this function we should re-write it to make it mimic the pytest.warns function.

**Comment by mkolopanis** [comment]
even use pytest under the hood too. Maybe that's already what you mean. Not that users can't just use pytest.warns to do exactly what checkWarnings does already though. I feel like there are arguments both ways.

**Comment by bhazelton** [comment]
we should also rename it to not use camel case, per issue #745
