### ISSUE TITLE
ant_str keyword for UVFlag.select

### ISSUE THREAD

**Issue by mwilensky768** [RadioAstronomySoftwareGroup/pyuvdata#841]
The `UVFlag.select` method does not have an `ant_str` keyword, which is an extremely convenient one for sorting autos from crosses. It would be nice to have this keyword.

**Comment by mwilensky768** [comment]
@mkolopanis

**Comment by mkolopanis** [comment]
Thanks for the ping. I think that I can get to this late this week or next.

**Comment by mkolopanis** [comment]
@bhazelton do we want to try moving `parse_ants` to utils and have it take a uvbased object as an input? Could re-write parse_ants but don't want to duplicate too much code.

**Comment by bhazelton** [comment]
I think that's fine. Definitely don't want to duplicate code!
