### ISSUE TITLE
UVFlag add method

### ISSUE THREAD

**Issue by mwilensky768** [RadioAstronomySoftwareGroup/pyuvdata#843]
Would it be possible to make it so that when calling `UVFlag.__add__`, it iterates over the `_data_params` property, rather than only the `metric_array`, `weights_array`, or `flag_array` attributes? See this [line](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/609e6c9ffc719fc1f2882772058b61e47f38b5f8/pyuvdata/uvflag/uvflag.py#L1557).

This is important if people are using the optional `weights_square_array`, or if people subclass `UVFlag` and create additional `_data_params` (SSINS does this [here](https://github.com/mwilensky768/SSINS/blob/836716f424fbdcffef0c6c583ac41d66bed30a17/SSINS/incoherent_noise_spectrum.py#L419).)

**Comment by mwilensky768** [comment]
I would do this with someone's blessing.

**Comment by mkolopanis** [comment]
Yeah that seems like a reasonable change I think. I would bet this line is carry over from before UVFlag subclassed UVBase. As long as it does not affect the current behavior, it sounds like a good change.

**Comment by mkolopanis** [comment]
did #844 close this?

**Comment by mwilensky768** [comment]
Yes.
