### ISSUE TITLE
Write memo describing coordinate systems and transformations

### ISSUE THREAD

**Issue by plaplant** [RadioAstronomySoftwareGroup/pyuvdata#845]
When reviewing #840, it occurred to me that we don't have a canonical reference for what we mean when we say ECEF vs ENU vs rotECEF (and that XYZ == ECEF), etc. There is [this reference memo in the docs folder](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/docs/references/GPS.G1-X-00006_Datum_Transformations.pdf), but I don't believe that has the level of specificity required to understand what is meant by the different systems (and doesn't include all systems we support). It would also be good to explain why we use the rotation matrices that we do to convert between the different systems.

**Comment by bhazelton** [comment]
@plaplant There's some nice coordinate system descriptions in the new [phasing memo](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/main/docs/references/phasing.pdf) that @kartographer wrote. Can you take a look and see if it meets your needs or whether we need to either add more to it or develop another memo?

**Comment by plaplant** [comment]
@kartographer very nice memo! Yes, I think the memo nicely describes different coordinate systems and what their meanings are. Happy to consider this done.
