### ISSUE TITLE
time_array and time_range are problematic in UVCal

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvdata#851]
time_array should be used, but time_range should be replaced by an integration_length-like array that defines what range of times the solution applies to.  This will require some work on uvcalibrate to interpret sensibly.

**Comment by bhazelton** [comment]
It makes sense to either have a `time_array` or a `time_range` (maybe rename?) defined. `time_range` should be 2D, with one axis length 2 to give the start/stop times and the other axis the length of the number of time solutions.

we will use `Ntimes` for either the length of the `time_array` or the number of time solutions (the second axis of the `time_range`).

**Comment by bhazelton** [comment]
We realized that this is a breaking change that can't be fully handled with deprecation, so it should happen in a major release.

**Comment by bhazelton** [comment]
This was fixed in #1306 and will be released in version 3.0
