### ISSUE TITLE
Remove "unknown" as a cal_type

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvdata#855]
cal_type unknown is not useful and should probably be removed.  Can just use None if initializing a blank object.  We can move "unknown" to cal_style.

**Comment by bhazelton** [comment]
The cal_type keyword controls the shapes of some of the arrays in the object, so I don't think that using None will work well. We implicitly default to the shapes associated with the "gain" type, so I'm inclined to default to that.
