### ISSUE TITLE
polarization concatenation order and possible errors in writing output files

### ISSUE THREAD

**Issue by jaguirre** [RadioAstronomySoftwareGroup/pyuvdata#888]
When concatenating files with different polarizations, the order in which they are read in (using the `read` method), or possibly added, can generate the error 

`Combined polarizations are not evenly spaced. This will make it impossible to write this data out to some file types.`

If the read order is `['xx','yy','xy','yx']` (AIPS ordering), this error is not generated.  The underlying problem is apparently that uvfits requires a specific order if all 4 are present.

Suggest allowing a read in any order (since pyuvdata doesn't appear to fundamentally care), but enforcing AIPS ordering on writing uvfits files (or other formats which require a particular order).

**Comment by bhazelton** [comment]
@plaplant thinks this will be fixed by only doing a check at the end of reading all the files rather than after every read. This may also speed things up.
