### ISSUE TITLE
Redundant baseline finding methods are very brittle on arrays containing a non-redundant component (e.g. MWA Phase II)

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvdata#893]
At least on MWA Phase II data, get_redundancies requires a lot of hand-holding.  I encountered two different issues:

(1) Using utils.get_baseline_redundancies throws a memory error, saying it would require 435 GiB.  Using UVData.get_redundancies on the object itself doesn't, but it's surprising to me to see different behavior.  (Note that the tutorial still suggests that the method in utils should be used.)

(2) Most any permutation of arguments throws "ValueError: Some baselines are falling into multiple redundant groups. Lower the tolerance to resolve ambiguity."  I needed to get the tolerance down to 1 mm to avoid this error and then redundant baselines were not really identified (i.e. too many groups with too few baselines per group).

Ultimately, I had to first run a select to remove the antennas that were not part of the hexes and then it worked better.  (Note that this didn't fix problem (1) -- although at this point it only says 76.3 GiB would have been necessary.)  Maybe it's just the case that running get_redundancies on a data set with lots of unique baselines is doomed to fail.  If that's the case, perhaps we just need to add some documentation warning users about which situations we expect things to work in.

**Comment by jpober** [comment]
Partial resolution: update the tutorial to use the method on the object (which uses a unique call to reduce the memory footprint).  We will add some documentation recommending only redundant baselines be input (i.e. non-redundant baselines should be removed with a select before running this method).  We should also standardize keywords between the utility function and the method.  A separate issue to improve the actual redundancy finder is being created.

**Comment by jsdillon** [comment]
An alternative solution to this and to #894 would be to use the grid based solution I use in hera_cal: https://github.com/HERA-Team/hera_cal/blob/eaecb78edf68b14a617b6d9b7b12e14abf95e908/hera_cal/redcal.py#L24

This algorithm scales roughly linearly with the number of baselines and doesn't require significant memory.

**Comment by aelanman** [comment]
These methods definitely aren't well-tested on semi-redundant arrays like MWA Phase II. It handles unique baselines as groups of size 1. I'm not entirely sure where the MemoryError is coming from... can you provide the stack trace?

The trouble, I think, that it just errors at the slightest ambiguity in redundancy. It might make more sense to treat ambiguous baselines as non-redundant.

The find_clusters method is almost certainly not the ideal approach here... I'm sure there are proper methods informed by comp-sci research for identifying points within a given distance of each other in a space. I fully support switching to the more lightweight grid method, provided it can pass the existing unit tests.

**Comment by jpober** [comment]
I finally took a look at this again.   I still get a very large memory error with utils.get_baseline_redundancies (but UVData.get_redundancies works fine).  @aelanman if you still have interest in digging into this, I created a minimal working example and put it in a folder called redundancy_mem_error in Oscar's shared directory.  For everyone else, still note that the tutorial still needs to be updated to steer users away from get_baseline_redundancies (at least until we can understand why it behaves differently).

**Comment by aelanman** [comment]
@jpober I looked over the mwe (sorry for the delay). With the changes in PR #976 , the memory error is no longer happening in your example, but it is still reporting some baselines as ambiguous at 1e-3 tolerance. So the memory error is fixed, but it's still a brittle function. If it's any help, it breaks faster this way.

Thinking back on my comment from Sep 28th, I don't think it's a simple question of how "ambiguous baselines" should be handled. Considering two or more baselines redundant to some tolerance means that we're assuming they make the same measurement to within error related to the position tolerance. It shouldn't be possible to have A = B and B = C but also A != C. So if the tolerance is high enough that this happens, it means it isn't a well-defined criterion for redundancy across the array.

We could think about switching to a tolerance relative to baseline length, or try to base the position tolerance on some fringe error tolerance?

**Comment by jpober** [comment]
Even if it's fixed now, do you have a sense for why utils.get_baseline_redundancies would give the memory error and UVData.get_redunancies wouldn't?  Are they doing anything fundamentally different?  If so, we should probably eliminate the sub-optimal method and update the tutorial accordingly.

As for ambiguous baselines, you raise a good point.  If A = B and B = C but A != C, I think the function should error as it's an indication the user needs to rethink their tolerances.  Is that the only situation where this error crops up?  If it is, we should make the error message a bit clearer.  If not, it might be worthwhile to think whether there's a way to raise a separate error for this particular situation.

**Comment by aelanman** [comment]
>do you have a sense for why utils.get_baseline_redundancies would give the memory error and UVData.get_redunancies wouldn't? Are they doing anything fundamentally different?
I think the reason is that `UVData.get_redundancies` first selects a single time from the `baseline_array` and `uvw_array` before running `get_baseline_redundancies`. In your example code, you were passing the full (length `Nblts`) arrays to `get_baseline_utilities`, which ends up using Ntimes**2 more memory (assuming Nblts = Ntimes * Nbls). When I selected just the first time from the file, the original method did not give a MemoryError.

>  Is that the only situation where this error crops up? 

It should be, but it's worrying that you see this error for MWA Phase II until you get down to mm tolerance. It might be nice if the error could also identify _which_ baselines were causing the error to come up.

**Comment by jpober** [comment]
I think there are two small-ish remaining issues before closing this:
(1) Make the with_conjugates keyword on get_baseline_redundancies match the include_conjugates keyword on UVData.get_redundancies (we favor changing with_conjugates to include_conjugates to be more consistent with other keywords, but either way there will need to be a deprecation period
(2) Make the tutorial clearer with an example of UVData.get_redundancies and perhaps say it is the preferred way of calling this.
