### ISSUE TITLE
Enhanced support for SMA Data

### ISSUE THREAD

**Issue by kartographer** [RadioAstronomySoftwareGroup/pyuvdata#902]
Following the completion of #899, we have a couple of residual issues that we'd like address in a future release, namely:

1. Increased unit testing, including the migration of SMA's FLARE tool (at least the parts specific to the MIR file format) over to `test_mir_parser.py`
2. Better support for auto-correlation data. At the moment, auto-correlations are read in by the `MirParser` class, but because of missing meta-information, we have elected not to include it as an option for export into `UVData`.

**Comment by e-koch** [comment]
* [ ] Propagate `has_auto` to `UVData` to enable loading the autocorrelation data. See #1020
