### ISSUE TITLE
reading UVH5 with metadata as bytes raises error

### ISSUE THREAD

**Issue by nkern** [RadioAstronomySoftwareGroup/pyuvdata#906]
I have an older UVH5 file where for whatever reason, some of the metadata are already in bytes form, which causes things like `header['telescope_name'].tobytes().decode('utf8')` to fail, b/c `header['telescope_name']` does not have a method `tobytes()`.

**Comment by plaplant** [comment]
@nkern I believe that was a very old issue with the early alpha version of UVH5 files. Support for reading files like that used to be handled by this function:

https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/d1829efacb60da384f64a8f25a280441bfa9d68a/pyuvdata/uvh5.py#L28-L54

However, as can be seen by the warning message, support for these types of files was officially deprecated in version 1.5 (and issued a `DeprecationWarning` for several minor versions before that). I am hesitant to make a fix for handling old files like these going forward, so I think the better solution is to install an old version of pyuvdata (v1.4.2 or earlier) and rewrite the files using that. (Or you can just insert the linked function into your local version to handle the rewriting.) At that point the rewritten files should be compatible with the current file format.

**Comment by nkern** [comment]
@plaplant I see. So the changes that I was going to make (about to push a PR) is to simply change instances of
`xyz.tobytes()` to `bytes(xyz)`, which automatically handles this issue. If you think this is too much of a change for a deprecated feature, then I will just go ahead and try to re-write all of my files. Otherwise, if you think this is fine, I'll just submit the PR. lmk

**Comment by plaplant** [comment]
Ah okay, I didn't realize that `bytes()` would handle it automatically. That seems like a small enough change, let's do it. Thanks for the fix!

**Comment by bhazelton** [comment]
This was fixed in #907.
