### ISSUE TITLE
Adding support for flexible spws with UVFlag objects

### ISSUE THREAD

**Issue by kartographer** [RadioAstronomySoftwareGroup/pyuvdata#916]
Following the merge of #909, `UVFlag` objects and methods now need to be updated to allow for the new handling of multiple spectral windows, and more generally to allow for the proper handling of the flexible spectral window feature found in `UVData`.

**Comment by jsdillon** [comment]
In particular, I need a `.use_future_array_shapes()` method in `UVFlag` in order to update `hera_qm` to eliminate the spw dimension (https://github.com/HERA-Team/hera_qm/pull/413), which in turn needs to be finished to do the same thing for hera_cal (https://github.com/HERA-Team/hera_cal/pull/797)

**Comment by jsdillon** [comment]
Looks like this can be closed, right @bhazelton @kartographer ?
