### ISSUE TITLE
Conjugation and UVW conventions are not specified in UVH5 memo

### ISSUE THREAD

**Issue by david-macmahon** [RadioAstronomySoftwareGroup/pyuvdata#924]
The UVH5 memo describes the `/Header/ant_1_array` and `/Header/ant_2_array` datasets that contain an antenna index for each baseline-time sample in `/Data/visdata` (et al.), but the memo does not specify the conjugation convention or UVW convention.  Is the visibility supposed to be `ant1 * conj(ant2)` or `conj(ant1) * ant2` or is it intentionally left unspecified?  Likewise, for the UVW values, are they `pos(ant1) - pos(ant2)` or `pos(ant2) - pos(ant1)`?  Are there any restrictions such as `ant1 <= ant2` for any given baseline-time sample?

**Comment by plaplant** [comment]
On our call today, I think we agreed that this conjugation convention is implicitly defined when one chooses the UVW convention, and is somewhat standard in the field (at least as far as correlators and CASA are concerned). Specifically, if the UVWs are `pos(ant2) - pos(ant1)`, then the visibilities are `ant1 * conj(ant2)`, and vice versa. UVH5 makes no restriction on the baseline ordering (unlike miriad's `ant1 <= ant2` constraint), but we should be explicit about these points in the memo.

**Comment by david-macmahon** [comment]
I was thinking about this and arrived at the same conclusion that so long as UVW and the visibilities are consistently handled there's really only two possibilities (so 100% chance of getting it wrong the first time 😜).  Is it correct to say that the convention you spelled out is for antenna signals that have undergone an even number of spectral flips (e.g. LSB mixes, second Nyquist zone sampling, etc.)?  It would be good to mention that aspect in the memo as well IMHO.

Being strict on the conjugation that goes into a dataset puts the onus on the dataset writer to ensure UVW/visdata consistency and requires a rewrite of one of them if it is written with inconsistent UVW/visdata.  Another option would be to add a flag that allows one to specify the conjugation convention used in the file, but then that puts the onus on downstream readers to be more "conjugation-agile".  I can see pros and cons to both ways and don't feel too strongly about either one.  I guess I slightly prefer the way it is now (i.e. only one correct way) since rewriting UVW is not too painful if the dataset writer gets things the wrong way around.
