### ISSUE TITLE
'select' function not correctly selecting by antenna_nums

### ISSUE THREAD

**Issue by Zhilei** [RadioAstronomySoftwareGroup/pyuvdata#928]
I found something unexpected when using the 'select' function:

After loading a .uvh5 data file
> UV = UVData()
UV.read(file)

I was trying to select a subgroup of the antennas via 
> UV_downselect = UV.select(antenna_nums=good_ants, inplace=False)

However, `UV_downselect.get_ants()` gives only a random subset of the good_ants list.

Here is a screenshot of the process:

![image](https://user-images.githubusercontent.com/9847573/93640029-ea201280-f9c7-11ea-836a-170a9ed36d07.png)

**Comment by bhazelton** [comment]
@Zhilei Thank you for the report. Can you give more information on how this file was created? What simulator was used? It's possible that not all the visibilities for every pair of antennas was present -- that can happen if only the redundant baselines are simulated for example. In that case, when you did the downselect, it would only keep visibilities that were between pairs of antennas in your `good_ants` list, which might reduce the number of total antennas with data associated with them. One way to test this is to use the `get_antpairs` method which will return all the pairs of antennas with data associated with them.

**Comment by Zhilei** [comment]
Thanks @bhazelton for the prompt response. @nkern brought up the same question so we tested with a simpler case which sets good_ants to a simpler list, and it gave the correct answer, as shown in the screenshot:
![image](https://user-images.githubusercontent.com/9847573/93641873-11c4aa00-f9cb-11ea-8ee7-39dae9d557e0.png)
So we think antenna 12, 13, 14 should have data but they were not picked in the first good_ants list.

**Comment by bhazelton** [comment]
I'm afraid that doesn't necessarily imply that they should have been included, because you included a bunch of new antennas in the`good_ants` list, which may be the ones that have visibilities associated with antennas 12, 13 and 14. Can you please print out the result of `get_antpairs` on the original object?

**Comment by Zhilei** [comment]
I think you are right @bhazelton. Here is the output of `get_antpairs()` with only 574 pairs.
Probably within the first `good_ant` list I provided, there are only four of them that can find baseline pairs in the pairs list.

Here is the exact output from `get_antpairs()`.
> [(0, 0),
 (0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (0, 5),
 (0, 6),
 (0, 7),
 (0, 8),
 (0, 9),
 (0, 10),
 (0, 11),
 (0, 12),
 (0, 13),
 (0, 14),
 (0, 15),
 (0, 16),
 (0, 17),
 (0, 18),
 (0, 19),
 (0, 20),
 (0, 21),
 (0, 23),
 (0, 24),
 (0, 25),
 (0, 26),
 (0, 27),
 (0, 28),
 (0, 29),
 (0, 30),
 (0, 31),
 (0, 32),
 (0, 33),
 (0, 36),
 (0, 37),
 (0, 38),
 (0, 39),
 (0, 40),
 (0, 41),
 (0, 42),
 (0, 43),
 (0, 44),
 (0, 45),
 (0, 46),
 (0, 47),
 (0, 50),
 (0, 51),
 (0, 52),
 (0, 53),
 (0, 54),
 (0, 55),
 (0, 56),
 (0, 57),
 (0, 58),
 (0, 59),
 (0, 60),
 (0, 61),
 (0, 65),
 (0, 66),
 (0, 67),
 (0, 68),
 (0, 69),
 (0, 70),
 (0, 71),
 (0, 72),
 (0, 73),
 (0, 74),
 (0, 75),
 (0, 76),
 (0, 81),
 (0, 82),
 (0, 83),
 (0, 84),
 (0, 85),
 (0, 86),
 (0, 87),
 (0, 88),
 (0, 89),
 (0, 90),
 (0, 91),
 (0, 92),
 (0, 98),
 (0, 99),
 (0, 100),
 (0, 101),
 (0, 102),
 (0, 103),
 (0, 104),
 (0, 105),
 (0, 106),
 (0, 107),
 (0, 108),
 (0, 109),
 (0, 116),
 (0, 117),
 (0, 118),
 (0, 119),
 (0, 120),
 (0, 121),
 (0, 122),
 (0, 123),
 (0, 124),
 (0, 125),
 (0, 126),
 (0, 127),
 (0, 135),
 (0, 136),
 (0, 137),
 (0, 138),
 (0, 139),
 (0, 140),
 (0, 141),
 (0, 142),
 (0, 143),
 (0, 144),
 (0, 145),
 (0, 146),
 (0, 155),
 (0, 156),
 (0, 157),
 (0, 158),
 (0, 159),
 (0, 160),
 (0, 161),
 (0, 162),
 (0, 163),
 (0, 164),
 (0, 177),
 (0, 178),
 (0, 179),
 (0, 180),
 (0, 181),
 (0, 182),
 (0, 183),
 (1, 11),
 (1, 22),
 (1, 23),
 (1, 34),
 (1, 36),
 (1, 47),
 (1, 50),
 (1, 61),
 (1, 65),
 (1, 76),
 (1, 81),
 (1, 92),
 (1, 98),
 (1, 109),
 (1, 116),
 (1, 127),
 (1, 135),
 (1, 146),
 (1, 166),
 (2, 11),
 (2, 22),
 (2, 23),
 (2, 34),
 (2, 36),
 (2, 47),
 (2, 50),
 (2, 61),
 (2, 65),
 (2, 76),
 (2, 81),
 (2, 92),
 (2, 98),
 (2, 109),
 (2, 116),
 (2, 127),
 (2, 135),
 (2, 146),
 (2, 166),
 (3, 11),
 (3, 22),
 (3, 23),
 (3, 34),
 (3, 36),
 (3, 47),
 (3, 50),
 (3, 61),
 (3, 65),
 (3, 76),
 (3, 81),
 (3, 92),
 (3, 98),
 (3, 109),
 (3, 116),
 (3, 127),
 (3, 146),
 (3, 166),
 (3, 187),
 (4, 11),
 (4, 22),
 (4, 23),
 (4, 34),
 (4, 36),
 (4, 47),
 (4, 50),
 (4, 61),
 (4, 65),
 (4, 76),
 (4, 81),
 (4, 92),
 (4, 98),
 (4, 109),
 (4, 127),
 (4, 146),
 (4, 166),
 (4, 187),
 (5, 11),
 (5, 22),
 (5, 23),
 (5, 34),
 (5, 36),
 (5, 47),
 (5, 50),
 (5, 61),
 (5, 65),
 (5, 76),
 (5, 81),
 (5, 92),
 (5, 109),
 (5, 127),
 (5, 146),
 (5, 166),
 (5, 187),
 (6, 11),
 (6, 22),
 (6, 23),
 (6, 34),
 (6, 36),
 (6, 47),
 (6, 50),
 (6, 61),
 (6, 65),
 (6, 76),
 (6, 92),
 (6, 109),
 (6, 127),
 (6, 146),
 (6, 166),
 (6, 187),
 (6, 207),
 (7, 11),
 (7, 22),
 (7, 23),
 (7, 34),
 (7, 36),
 (7, 47),
 (7, 50),
 (7, 61),
 (7, 76),
 (7, 92),
 (7, 109),
 (7, 127),
 (7, 146),
 (7, 166),
 (7, 187),
 (7, 207),
 (8, 11),
 (8, 22),
 (8, 23),
 (8, 34),
 (8, 36),
 (8, 47),
 (8, 61),
 (8, 76),
 (8, 92),
 (8, 109),
 (8, 127),
 (8, 146),
 (8, 166),
 (8, 187),
 (8, 207),
 (9, 11),
 (9, 22),
 (9, 23),
 (9, 34),
 (9, 47),
 (9, 61),
 (9, 76),
 (9, 92),
 (9, 109),
 (9, 127),
 (9, 146),
 (9, 166),
 (9, 187),
 (9, 207),
 (10, 22),
 (10, 34),
 (10, 47),
 (10, 61),
 (10, 76),
 (10, 92),
 (10, 109),
 (10, 127),
 (10, 146),
 (10, 166),
 (10, 187),
 (11, 155),
 (11, 156),
 (11, 157),
 (11, 158),
 (11, 159),
 (11, 160),
 (11, 161),
 (11, 162),
 (11, 163),
 (11, 164),
 (11, 165),
 (12, 155),
 (13, 22),
 (13, 155),
 (14, 22),
 (15, 22),
 (16, 22),
 (17, 22),
 (18, 22),
 (19, 22),
 (20, 22),
 (21, 22),
 (22, 25),
 (22, 26),
 (22, 27),
 (22, 28),
 (22, 29),
 (22, 30),
 (22, 31),
 (22, 32),
 (22, 33),
 (22, 39),
 (22, 40),
 (22, 41),
 (22, 42),
 (22, 43),
 (22, 44),
 (22, 45),
 (22, 46),
 (22, 54),
 (22, 55),
 (22, 56),
 (22, 57),
 (22, 58),
 (22, 59),
 (22, 60),
 (22, 69),
 (22, 70),
 (22, 71),
 (22, 72),
 (22, 73),
 (22, 74),
 (22, 75),
 (22, 86),
 (22, 87),
 (22, 88),
 (22, 89),
 (22, 90),
 (22, 91),
 (22, 104),
 (22, 105),
 (22, 106),
 (22, 107),
 (22, 108),
 (22, 123),
 (22, 124),
 (22, 125),
 (22, 126),
 (22, 144),
 (22, 145),
 (22, 165),
 (22, 187),
 (22, 188),
 (22, 189),
 (22, 190),
 (22, 191),
 (22, 192),
 (22, 193),
 (22, 194),
 (22, 195),
 (22, 207),
 (22, 208),
 (22, 209),
 (22, 210),
 (22, 211),
 (22, 212),
 (22, 213),
 (22, 214),
 (23, 155),
 (23, 156),
 (23, 157),
 (23, 158),
 (23, 159),
 (23, 160),
 (23, 161),
 (23, 162),
 (23, 163),
 (23, 164),
 (23, 165),
 (24, 155),
 (34, 163),
 (34, 164),
 (34, 165),
 (34, 186),
 (34, 206),
 (36, 155),
 (36, 156),
 (36, 157),
 (36, 158),
 (36, 159),
 (36, 160),
 (36, 161),
 (36, 162),
 (36, 163),
 (36, 164),
 (36, 165),
 (37, 155),
 (47, 162),
 (47, 163),
 (47, 164),
 (47, 165),
 (47, 186),
 (50, 155),
 (50, 156),
 (50, 157),
 (50, 158),
 (50, 159),
 (50, 160),
 (50, 161),
 (50, 162),
 (50, 163),
 (50, 164),
 (50, 165),
 (50, 186),
 (51, 155),
 (61, 161),
 (61, 162),
 (61, 163),
 (61, 164),
 (61, 165),
 (61, 186),
 (65, 155),
 (65, 156),
 (65, 157),
 (65, 158),
 (65, 159),
 (65, 160),
 (65, 161),
 (65, 162),
 (65, 163),
 (65, 164),
 (65, 165),
 (65, 186),
 (66, 155),
 (76, 160),
 (76, 161),
 (76, 162),
 (76, 163),
 (76, 164),
 (76, 165),
 (76, 186),
 (81, 155),
 (81, 156),
 (81, 157),
 (81, 158),
 (81, 159),
 (81, 160),
 (81, 161),
 (81, 162),
 (81, 163),
 (81, 164),
 (81, 165),
 (81, 186),
 (82, 155),
 (92, 159),
 (92, 160),
 (92, 161),
 (92, 162),
 (92, 163),
 (92, 164),
 (92, 165),
 (92, 186),
 (98, 155),
 (98, 156),
 (98, 157),
 (98, 158),
 (98, 159),
 (98, 160),
 (98, 161),
 (98, 162),
 (98, 163),
 (98, 164),
 (98, 165),
 (98, 186),
 (99, 155),
 (109, 158),
 (109, 159),
 (109, 160),
 (109, 161),
 (109, 162),
 (109, 163),
 (109, 164),
 (109, 165),
 (109, 186),
 (116, 155),
 (116, 156),
 (116, 157),
 (116, 158),
 (116, 159),
 (116, 160),
 (116, 161),
 (116, 162),
 (116, 163),
 (116, 164),
 (116, 165),
 (117, 155),
 (127, 157),
 (127, 158),
 (127, 159),
 (127, 160),
 (127, 161),
 (127, 162),
 (127, 163),
 (127, 164),
 (127, 165),
 (127, 186),
 (135, 155),
 (135, 156),
 (135, 157),
 (135, 158),
 (135, 159),
 (135, 160),
 (135, 161),
 (135, 162),
 (135, 163),
 (135, 164),
 (135, 165),
 (136, 155),
 (146, 157),
 (146, 158),
 (146, 159),
 (146, 160),
 (146, 161),
 (146, 162),
 (146, 163),
 (146, 164),
 (146, 165),
 (146, 186),
 (155, 205),
 (155, 223),
 (155, 240),
 (155, 256),
 (155, 271),
 (155, 285),
 (155, 298),
 (155, 310),
 (156, 166),
 (157, 166),
 (157, 187),
 (158, 166),
 (158, 187),
 (159, 166),
 (159, 187),
 (160, 166),
 (160, 187),
 (161, 166),
 (161, 187),
 (162, 166),
 (162, 187),
 (163, 166),
 (163, 187),
 (164, 166),
 (164, 187),
 (165, 166),
 (165, 187),
 (166, 186)]

**Comment by bhazelton** [comment]
Ok, great, that makes sense. If this simulation only simulates redundant baselines and you'd like to inflate the data set to copy those visibilities to the matching baselines that are not included in the data set, you can try using the `inflate_by_redundancy` method on `UVData`.

**Comment by Zhilei** [comment]
Oh, great! I will try the `inflate_by_redundancy` method. That will be so handy. Thank you so much for the help, I will close the issue then.
