### ISSUE TITLE
Antenna positions in `pyuvdata/data/zen.2458432.34569.uvh5` use incorrect coordinate frame

### ISSUE THREAD

**Issue by david-macmahon** [RadioAstronomySoftwareGroup/pyuvdata#936]
As mentioned in #922, the `pyuvdata/data/zen.2458432.34569.uvh5` file has antenna positions that appear to be in an Earth Centered frame that is rotated from the ECEF ITRF frame.  This differs from all that other UVH5 files in `pyuvdata/data` in that 1) it is the only file that has Earth Centered antenna positions and 2) the coordinate frame is rotated such that the "X" axis points to the local meridian rather than 0 longitude.  If this file exists as an intentional "error case" it should be given a more descriptive name so that it will not be mistaken as an example of correct antenna positions.  If it's not an intentional error, this file should be corrected or removed to avoid confusion.

**Comment by bhazelton** [comment]
Thank you for finding this. It was apparently a file we wrote very early on before we'd fully shaken out the uvh5 format. @plaplant will update this file in his branch where he's fixing up the memo.
