### ISSUE TITLE
Add get_nsamples method

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvdata#944]
We have methods called get_data and get_flags which are very useful, but no similar way to access to the nsample_array.

**Comment by mkolopanis** [comment]
Is there functionality this is missing?

**Comment by mkolopanis** [comment]
I'm a little confused by this. It looks like this function does exist on UVData objects. Is there functionality missing from it?

https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/eedb1e10ef2af8e4a019e7df2abed012d23c6471/pyuvdata/uvdata/uvdata.py#L1723-L1775

**Comment by jpober** [comment]
Yup, and it's even described in the tutorial.  Never mind!  Not sure how I missed that.
