### ISSUE TITLE
Init UVData from filename

### ISSUE THREAD

**Issue by mkolopanis** [RadioAstronomySoftwareGroup/pyuvdata#949]
Should we allow a optional filename (or list) to be passed to init to also read files after initialization of UVData objects? This would also require piping all `read` kwargs up to init.

**Comment by bhazelton** [comment]
Another option is to use a class method like `read_from` to make reading in a file a one-liner.

**Comment by bhazelton** [comment]
We leaned towards a class method rather than doing it in the init on the 8/4/21 telecon.

**Comment by steven-murray** [comment]
I'd definitely support the classmethod approach
