### ISSUE TITLE
Large memory required for gpubox file reading

### ISSUE THREAD

**Issue by nicholebarry** [RadioAstronomySoftwareGroup/pyuvdata#954]
I am unable to read all of the gpubox files for one observation on our cluster due to the large memory requirements needed to read in the gpubox files.

- Time/freq resolution is 0.5s/40kHz
- Each gpubox file is less than 2Gb
- There are 24 channels with 2 gpubox files each

Below is a sample script. I am only reading in approx 1/4 of the gpubox files at once in this example.
```
from pyuvdata import UVData
import numpy as np
UV = UVData()

# Construct the list of files
data_path = '/fred/oz048/MWA/data/1061316296/rts_thermal_noise/'
filelist = [data_path + i for i in ['1061316296.metafits',
     '1061316296_thermal01_00.fits','1061316296_thermal01_01.fits',
     '1061316296_thermal02_00.fits','1061316296_thermal02_01.fits',
     '1061316296_thermal03_00.fits','1061316296_thermal03_01.fits',
     '1061316296_thermal04_00.fits','1061316296_thermal04_01.fits',
     '1061316296_thermal05_00.fits','1061316296_thermal05_01.fits',
     '1061316296_thermal06_00.fits','1061316296_thermal06_01.fits']]
UV.read(filelist, correct_cable_len=True, phase_to_pointing_center=True, flag_init=False,data_array_dtype=np.complex64)
write_file = '/fred/oz048/MWA/data/1061316296/rts_thermal_noise/1061316296_1.uvfits'
UV.write_uvfits(write_file, spoof_nonessential=True)
```

Below is the CPU usage and memory allocation for a job run on the above script. Blue indicates user processes (calculations), green indicates system processes (I/O), yellow indicates memory, and dashed yellow is the allocated memory. The job was killed before all files were read. 
<img width="578" alt="Screen Shot 2020-12-04 at 9 49 41 pm" src="https://user-images.githubusercontent.com/5588290/101155247-f2a8f080-367a-11eb-8243-b9c88f2c00f0.png">

**Comment by mkolopanis** [comment]
Posting a comment here as I am working through this.
Also looking at 24 channels x 2 boxes per file. .5s integrations, 40kHz frequency resolution. 

I see a peak memory usage around 111GiB and the fully read object sits around ~70GB (65 GiB). This is after a few changes which should help, but still sounds like a considerable overhead.
