### ISSUE TITLE
Should we build against python 3.9 rather than 3.6?

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyuvdata#957]
python 3.6 is only getting security updates now (actually, so is 3.7) and 3.9 has been out for a few months. End of life for 3.6 is currently set for December 2021. I don't really want to build against 4 versions because of how long it takes to run the tests, but we can if we think we need to.

**Comment by mkolopanis** [comment]
A note about 3.9: as of this post, still some conda build inconsistencies between what I suspect is h5py and python-casacore preventing us from testing against it. You can brute force it though and just build everything with `pip`.
