### ISSUE TITLE
Timestamps after compressing baselines

### ISSUE THREAD

**Issue by Zhilei** [RadioAstronomySoftwareGroup/pyuvdata#975]
This issue has come up earlier which I did not follow up closely. Here is the detailed issue report:

After I have a HERA data object read in as `hd`, I averaged the baselines with

`hd_red_avg = hd.compress_by_redundancy(tol=1,
                                       method='average',
                                       inplace=False,
                                       keep_all_metadata=False)`

The original `hd` object has 60 integrations, so naturally, I would expect the new `hd_red_avg` object have that many integrations as well.

Under the `hd_red_avg` object, the `Ntimes` attribute gives 153; the `times` attribute gives an array of 60 jd values, as expected. The `times_array` attribute gives an array with a length of Nblts. If I do 

`np.unique(hd_red_avg.times_array)`, 

I got an array of 153 elements. 

And if I do

`np.diff(np.unique(hd_red_avg.times_array))`, 

I found the differences come in two groups: 10^-4 (expected) and 10^-10 (seems to be some numerical rounding errors). 

I am not sure where this happens on a lower level, but I hope this can be useful for debugging the issue. The 153 number may change for different data sets, but the inconsistency is normally there.

Please feel free to let me know if I can provide more information. Thank you so much!

**Comment by bhazelton** [comment]
Thanks for reporting this in detail @Zhilei! Sorry it took awhile to address, but there's a PR now (#984) that I hope will fix this problem. I haven't yet reproduced this problem with any of our test datasets, I'm still working on that. But if you'd like to checkout the branch in that PR and let us know if it fixes the problem we'd appreciate it.

**Comment by bhazelton** [comment]
Update: I have now reproduced your issue with one of our test datasets and can confirm that the PR fixes the problem in that dataset.

**Comment by Zhilei** [comment]
Thank you so much for getting back on this! I did not notice this until Jackie mentioned that this issue is closed. And I see the issue is even merged, I will update my pyuvdata copy then. Thank you so much!
