### ISSUE TITLE
Type `None` vs empty dict in uvflag.extra_keywords

### ISSUE THREAD

**Issue by no-lex** [RadioAstronomySoftwareGroup/pyuvdata#977]
See #974 for the context of this issue.

In working on #974, there was some nuance between the choice of `None` and `{}` (empty dict) for the default value of `extra_keywords`. The default is `{}` in both UVFlag and UVData, and it works acceptably, being able to compare to `None` might be more intuitive.

Handling `{}` for #974 also resulted in somewhat sloppier code than what would have been done otherwise.

If there is a compatibility reason for `extra_keywords` to always be initialized as at least an empty dict then it's not a problem to leave it as-is.

**Comment by bhazelton** [comment]
I think we'll leave this as is. It's not clear that it would make things vastly simpler and we're concerned that there may be a fair bit of existing code that assumes this behavior (e.g. iterating without checking that it's not None).
