### ISSUE TITLE
antpos from UVData.get_ENU_antpos() is F_CONTIGUOUS not C_CONTIGUOUS; affects hera_gpu

### ISSUE THREAD

**Issue by hughbg** [RadioAstronomySoftwareGroup/pyuvdata#981]
- What version of python and pyuvsim am I using?

Python 3.7.6
pyuvdata 2.1.3  

- What operating system am I using?

Scientific Linux release 7.9 (Nitrogen)

- What did I do?

I printed the flags of the antpos numpy array that is returned by the get_ENU_antpos() method of the UVData object. I did this while running hera_sim and using the GPU code in hera_gpu. I got these flag values:

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

- What did I expect to see?

That the array is in C order, i.e. C_CONTIGUOUS : True

- What did I see instead?

That the array is in FORTRAN order, i.e. F_CONTIGUOUS : True

- Any code to reproduce the bug (as minimal an example as possible)?

Print the antpos flags when antpos is returned from get_ENU_antpos().
```
 print(antpos.flags)
```

- Why is this important?

The GPU code in hera_gpu assumes the antpos array is in C order, and because it’s not, I get incorrect values. I can easily fix this in hera_gpu of course. I'm not sure if you intended to use FORTRAN order but C order would be more expected.

This is totally separate from the order of array values that are produced if you print the array in Python. It's a low-level thing.

**Comment by mkolopanis** [comment]
Very interesting. I would guess there is a transpose at some point before the value is returned. I understand this isn't the solution you're looking for, but as a gap-stop you can wrap the `hera_gpu` input in an `np.ascontiguousarray` to ensure you get C-Contiguous arrays for your code. 

In the long term we can figure out what exactly we want from our arrays. I would naively too expect everything to be C-Contiguous.

**Comment by bhazelton** [comment]
The memory order of the arrays in pyuvdata isn't really an API level specification, so I'm not sure we can guarantee any particular ordering in general. I think in your case it's probably safer to use the numpy functions to get it in the order you require before you use it in code that requires a specific ordering. You might take a look at both `np.require` and `np.ascontiguousarray` as options to achieve what you need.

**Comment by hughbg** [comment]
More information: The actual ordering of antpos is "weird". Although the above report indicates that the array is in FORTRAN order, transposing the array doesn't fix the problem. And the subarrays don't show any ordering. For example:

  print(antpos[0].flags)

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In any case. using np.ascontiguousarray *does* fix the problem. It forces C order.

**Comment by bhazelton** [comment]
I'm glad `np.ascontiguousarray` fixes the problem. Within pyuvdata, we allow numpy to manage the memory order, which is why I don't think we can guarantee any particular memory ordering in general.
